version: '3.8'
services:
  app:
    container_name: microservicios-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432  # Este debe ser el puerto interno del contenedor PostgreSQL
      - DB_USER=postgres
      - DB_PASSWORD=2620ac 
      - DB_DATABASE=microservices_db
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - microservice-network

  db:
    container_name: microservicios-db
    image: postgres:17
    ports:
      - "5433:5432"  # Exponemos el puerto 5433 en la máquina host, pero internamente es el puerto 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2620ac  
      POSTGRES_DB: microservices_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservice-network

volumes:
  postgres-data:

networks:
  microservice-network:
