version: '3.8'
services:
  app:
    container_name: microservicios-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=2620ac
      - DB_DATABASE=microservices_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - microservice-network

  db:
    container_name: microservicios-db
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2620ac
      POSTGRES_DB: microservices_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/ # Montar carpeta con scripts SQL
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  microservice-network: