version: '3.8'
services:
  app:
    container_name: microservicios-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN} # Token cargado desde el entorno o manualmente
    command: doppler run -- npm start # Ejecuta la aplicación usando Doppler
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - microservice-network

  db:
    container_name: microservicios-db
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    command: doppler run -- postgres # Ejecuta PostgreSQL usando Doppler para cargar variables
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  microservice-network: