
CREATE TABLE TA_PLANTARIF
(
  COD_PRODUCTO       NUMBER(1)                  NOT NULL,
  COD_PLANTARIF      VARCHAR2(3 BYTE)           NOT NULL,
  DES_PLANTARIF      VARCHAR2(30 BYTE)          NOT NULL,
  TIP_TERMINAL       VARCHAR2(1 BYTE),
  COD_LIMCONSUMO     VARCHAR2(3 BYTE)           NOT NULL,
  COD_CARGOBASICO    VARCHAR2(3 BYTE)           NOT NULL,
  TIP_PLANCONSUMO    NUMBER(2)                  NOT NULL,
  TIP_PLANTARIF      VARCHAR2(1 BYTE)           NOT NULL,
  NUM_MINUTOSFF      NUMBER(6),
  IMP_MINUTOFF       NUMBER(12,4),
  TIP_UNIDADES       VARCHAR2(1 BYTE)           NOT NULL,
  NUM_UNIDADES       NUMBER(6)                  NOT NULL,
  IND_ARRASTRE       NUMBER(1)                  NOT NULL,
  NUM_DIAS           NUMBER(3)                  NOT NULL,
  NUM_ABONADOS       NUMBER(5),
  FEC_DESDE          DATE                       NOT NULL,
  FEC_HASTA          DATE,
  IND_FAMILIAR       NUMBER(1)                  DEFAULT 0                     NOT NULL,
  NOM_USUARIO        VARCHAR2(40 BYTE)          DEFAULT 'TARIFICA'            NOT NULL,
  FEC_ULTIMAMOD      DATE                       DEFAULT '01-jan-99'           NOT NULL,
  TIP_UNITAS         CHAR(1 BYTE)               DEFAULT 'M'                   NOT NULL,
  IND_TARIFADIFER    NUMBER(1)                  DEFAULT 0                     NOT NULL,
  CLA_PLANTARIF      VARCHAR2(3 BYTE),
  IND_PROPORCS       NUMBER(1)                  DEFAULT 0,
  IND_CARGO_HABIL    NUMBER(1)                  DEFAULT 0,
  NUM_DIAS_EXPIRA    NUMBER(3)                  DEFAULT 0,
  COD_PLAN_COMVERSE  VARCHAR2(2 BYTE),
  IND_FRANCONS       VARCHAR2(2 BYTE)           DEFAULT 'M'                   NOT NULL,
  COD_SERVICIO       VARCHAR2(5 BYTE),
  COD_TIPLAN         VARCHAR2(5 BYTE),
  IND_COBRA_SEND     NUMBER(1)                  DEFAULT 1                     NOT NULL,
  IND_BOLSADCTO      VARCHAR2(5 BYTE)           DEFAULT 'C'                   NOT NULL,
  FLG_RANGO          NUMBER(1)                  DEFAULT 0,
  IND_COMER_WEB      NUMBER(1)                  DEFAULT 0                     NOT NULL,
  COD_PROD_PADRE     NUMBER(8),
  NUM_MESES_RENOVA   NUMBER(2)                  DEFAULT 0                     NOT NULL,
  TIP_RED            VARCHAR2(1 BYTE)           DEFAULT 'M'                   NOT NULL,
  IND_COMPARTIDO     NUMBER(1)                  DEFAULT 0,
  TIP_COBRO          VARCHAR2(1 BYTE)           DEFAULT 'V',
  GRP_PRESTACION     VARCHAR2(5 BYTE)           DEFAULT 'TM'                  NOT NULL,
  COD_GRUPO          VARCHAR2(5 BYTE)           DEFAULT '0'                   NOT NULL,
  COD_PRESTACION     VARCHAR2(5 BYTE)           DEFAULT '01',
  DUR_MINIMA         NUMBER(6)                  DEFAULT 0,
  GRP_PLAN           VARCHAR2(5 BYTE)
);




CREATE INDEX AK_TA_PLANTARIF_CODLIMCONS ON TA_PLANTARIF
(COD_PRODUCTO, COD_LIMCONSUMO);


CREATE INDEX AK_TA_PLANTARIF_TIPPLANTARIF ON TA_PLANTARIF
(TIP_PLANTARIF);


CREATE INDEX GE_TAPT_GRPCOD_PRESTACION_IE ON TA_PLANTARIF
(FEC_DESDE, FEC_HASTA, GRP_PRESTACION, COD_PRESTACION);


CREATE INDEX GE_TAPT_GRP_PRESTACION_IE ON TA_PLANTARIF
(FEC_DESDE, FEC_HASTA, GRP_PRESTACION);


CREATE UNIQUE INDEX PK_TA_PLANTARIF ON TA_PLANTARIF
(COD_PRODUCTO, COD_PLANTARIF);


CREATE INDEX X01TA_PLANTARIF ON TA_PLANTARIF
(COD_PLANTARIF);


ALTER TABLE TA_PLANTARIF ADD (
  CONSTRAINT PK_TA_PLANTARIF
  PRIMARY KEY
  (COD_PRODUCTO, COD_PLANTARIF)
  USING INDEX PK_TA_PLANTARIF);

ALTER TABLE TA_PLANTARIF ADD (
  CONSTRAINT FK_PLANTARIF_LIMCONSUMO 
  FOREIGN KEY (COD_PRODUCTO, COD_LIMCONSUMO) 
  REFERENCES TA_LIMCONSUMO (COD_PRODUCTO,COD_LIMCONSUMO)  DISABLE,
  CONSTRAINT FK_PLANTARIF_PRODUCTO 
  FOREIGN KEY (COD_PRODUCTO) 
  REFERENCES GE_PRODUCTOS (COD_PRODUCTO)  DISABLE);



-------------------------------------------------------

CREATE TABLE GE_CATEGORIAS
(
  COD_CATEGORIA        NUMBER(4)                NOT NULL,
  DES_CATEGORIA        VARCHAR2(50 BYTE)        NOT NULL,
  IND_ASESOR           CHAR(1 BYTE)             DEFAULT 'S',
  IND_VIGENCIA         CHAR(1 BYTE)             DEFAULT 'S',
  FEC_IND_VIGENCIA     DATE                     DEFAULT sysdate,
  NOM_USU_INDVIGENCIA  VARCHAR2(30 BYTE)        DEFAULT user,
  FEC_ULTMOD           DATE                     DEFAULT sysdate,
  NOM_USUARIO          VARCHAR2(30 BYTE)        DEFAULT user
);


CREATE UNIQUE INDEX PK_GE_CATEGORIAS ON GE_CATEGORIAS
(COD_CATEGORIA);



ALTER TABLE GE_CATEGORIAS ADD (
  CONSTRAINT PK_GE_CATEGORIAS
  PRIMARY KEY
  (COD_CATEGORIA)
  USING INDEX PK_GE_CATEGORIAS);

  
-----------------------------------------------------------------------  
  
  

CREATE TABLE GE_CLASCTA
(
  COD_CLASCTA  VARCHAR2(2 BYTE)                 NOT NULL,
  DES_CLASCTA  VARCHAR2(30 BYTE)                NOT NULL
);


CREATE UNIQUE INDEX PK_GE_CLASCTA ON GE_CLASCTA
(COD_CLASCTA);


ALTER TABLE GE_CLASCTA ADD (
  CONSTRAINT PK_GE_CLASCTA
  PRIMARY KEY
  (COD_CLASCTA)
  USING INDEX PK_GE_CLASCTA);

----------------------------------------------------------------------

  CREATE TABLE GE_TIPIDENT
(
  COD_TIPIDENT      VARCHAR2(2 BYTE)            NOT NULL,
  DES_TIPIDENT      VARCHAR2(20 BYTE)           NOT NULL,
  IND_PERTRIB       VARCHAR2(1 BYTE)            NOT NULL,
  IND_SALEFACT      NUMBER(1)                   NOT NULL,
  ORDEN_DISPLAY     NUMBER(2),
  IND_TIPIDENT      NUMBER(1),
  COD_TIPIDENTDIAN  VARCHAR2(2 BYTE)
);


CREATE UNIQUE INDEX PK_GE_TIPIDENT ON GE_TIPIDENT
(COD_TIPIDENT);



ALTER TABLE GE_TIPIDENT ADD (
  CONSTRAINT PK_GE_TIPIDENT
  PRIMARY KEY
  (COD_TIPIDENT)
  USING INDEX PK_GE_TIPIDENT);

--------------------------------------------------------------------

  
 CREATE TABLE GE_TIPTARJETAS
(
  COD_TIPTARJETA    VARCHAR2(3 BYTE)            NOT NULL,
  DES_TIPTARJETA    VARCHAR2(40 BYTE)           NOT NULL,
  IND_VALBIN        NUMBER(1)                   DEFAULT 0                     NOT NULL,
  COD_TARJETA_ASOC  VARCHAR2(3 BYTE)
);


CREATE UNIQUE INDEX PK_GE_TIPTARJETAS ON GE_TIPTARJETAS
(COD_TIPTARJETA);



ALTER TABLE GE_TIPTARJETAS ADD (
  CONSTRAINT PK_GE_TIPTARJETAS
  PRIMARY KEY
  (COD_TIPTARJETA)
  USING INDEX PK_GE_TIPTARJETAS);

----------------------------------------------------------

CREATE TABLE GE_SUCURSALES
(
  COD_BANCO      VARCHAR2(15 BYTE)              NOT NULL,
  COD_SUCURSAL   VARCHAR2(4 BYTE)               NOT NULL,
  DES_SUCURSAL   VARCHAR2(50 BYTE)              NOT NULL,
  COD_DIRECCION  NUMBER(20)                     NOT NULL
);


CREATE INDEX AK_GE_SUCURSALES_GE_DIRECCION ON GE_SUCURSALES
(COD_DIRECCION);


CREATE UNIQUE INDEX PK_GE_SUCURSALES ON GE_SUCURSALES
(COD_BANCO, COD_SUCURSAL);



ALTER TABLE GE_SUCURSALES ADD (
  CONSTRAINT PK_GE_SUCURSALES
  PRIMARY KEY
  (COD_BANCO, COD_SUCURSAL)
  USING INDEX PK_GE_SUCURSALES);

ALTER TABLE GE_SUCURSALES ADD (
  CONSTRAINT FK_GE_SUCURSALES_GE_BANCOS 
  FOREIGN KEY (COD_BANCO) 
  REFERENCES GE_BANCOS (COD_BANCO)  DISABLE);

----------------------------------------------------------  

CREATE TABLE GE_SISPAGO
(
  COD_SISPAGO  NUMBER(2)                        NOT NULL,
  DES_SISPAGO  VARCHAR2(40 BYTE)                NOT NULL,
  IND_INTERNO  NUMBER(1)                        NOT NULL,
  IND_MANUAL   NUMBER(1)                        NOT NULL
);


CREATE UNIQUE INDEX PK_GE_SISPAGO ON GE_SISPAGO
(COD_SISPAGO);



ALTER TABLE GE_SISPAGO ADD (
  CONSTRAINT PK_GE_SISPAGO
  PRIMARY KEY
  (COD_SISPAGO)
  USING INDEX PK_GE_SISPAGO);

---------------------------------------------------------
CREATE TABLE GE_PAISES
(
  COD_PAIS  VARCHAR2(3 BYTE)                    NOT NULL,
  DES_PAIS  VARCHAR2(30 BYTE)                   NOT NULL
);


CREATE UNIQUE INDEX PK_GE_PAISES ON GE_PAISES
(COD_PAIS);



ALTER TABLE GE_PAISES ADD (
  CONSTRAINT PK_GE_PAISES
  PRIMARY KEY
  (COD_PAIS)
  USING INDEX PK_GE_PAISES);

  
------------------------------------------------------------

  CREATE TABLE GE_REGIONES
(
  COD_REGION  VARCHAR2(3 BYTE)                  NOT NULL,
  DES_REGION  VARCHAR2(30 BYTE)                 NOT NULL
);


CREATE UNIQUE INDEX PK_GE_REGIONES ON GE_REGIONES
(COD_REGION);



ALTER TABLE GE_REGIONES ADD (
  CONSTRAINT PK_GE_REGIONES
  PRIMARY KEY
  (COD_REGION)
  USING INDEX PK_GE_REGIONES);



------------------------------------------------------------

CREATE TABLE GE_PROVINCIAS
(
  COD_PROVINCIA  VARCHAR2(5 BYTE)               NOT NULL,
  COD_REGION     VARCHAR2(3 BYTE)               NOT NULL,
  DES_PROVINCIA  VARCHAR2(30 BYTE)              NOT NULL,
  TIP_ZONA       VARCHAR2(1 BYTE)               DEFAULT 'M'                   NOT NULL
);


CREATE UNIQUE INDEX PK_GE_PROVINCIAS ON GE_PROVINCIAS
(COD_PROVINCIA, COD_REGION);


ALTER TABLE GE_PROVINCIAS ADD (
  CONSTRAINT PK_GE_PROVINCIAS
  PRIMARY KEY
  (COD_PROVINCIA, COD_REGION)
  USING INDEX PK_GE_PROVINCIAS);

ALTER TABLE GE_PROVINCIAS ADD (
  CONSTRAINT FK_PROVINCIA_REGION 
  FOREIGN KEY (COD_REGION) 
  REFERENCES GE_REGIONES (COD_REGION)  DISABLE);

  
--------------------------------------------------------

CREATE TABLE GE_COMUNAS
(
  COD_REGION     VARCHAR2(3 BYTE)               NOT NULL,
  COD_PROVINCIA  VARCHAR2(5 BYTE)               NOT NULL,
  COD_COMUNA     VARCHAR2(5 BYTE)               NOT NULL,
  DES_COMUNA     VARCHAR2(30 BYTE)              NOT NULL
);


CREATE UNIQUE INDEX PK_GE_COMUNAS ON GE_COMUNAS
(COD_REGION, COD_PROVINCIA, COD_COMUNA);


CREATE UNIQUE INDEX UK_GECOMUNAS_CODCOMUNA ON GE_COMUNAS
(COD_COMUNA);


ALTER TABLE GE_COMUNAS ADD (
  CONSTRAINT PK_GE_COMUNAS
  PRIMARY KEY
  (COD_REGION, COD_PROVINCIA, COD_COMUNA)
  USING INDEX PK_GE_COMUNAS,
  CONSTRAINT UK_GECOMUNAS_CODCOMUNA
  UNIQUE (COD_COMUNA)
  USING INDEX UK_GECOMUNAS_CODCOMUNA);

ALTER TABLE GE_COMUNAS ADD (
  CONSTRAINT FK_COMUNA_PROVINCIA 
  FOREIGN KEY (COD_PROVINCIA, COD_REGION) 
  REFERENCES GE_PROVINCIAS (COD_PROVINCIA,COD_REGION)  DISABLE);

------------------------------------------------------
  
 
CREATE TABLE GE_OFICINAS
(
  COD_OFICINA          VARCHAR2(2 BYTE)         NOT NULL,
  DES_OFICINA          VARCHAR2(40 BYTE)        NOT NULL,
  NOM_CONTACTO         VARCHAR2(40 BYTE)        NOT NULL,
  COD_REGION           VARCHAR2(3 BYTE),
  COD_PROVINCIA        VARCHAR2(5 BYTE),
  COD_COMUNA           VARCHAR2(5 BYTE),
  COD_DIRECCION        NUMBER(20)               NOT NULL,
  NUM_TELEF1           VARCHAR2(15 BYTE),
  NUM_TELEF2           VARCHAR2(15 BYTE),
  NUM_FAX              VARCHAR2(15 BYTE),
  OBS_OFICINA          VARCHAR2(255 BYTE),
  IND_REG_NECESIDADES  NUMBER(1)                DEFAULT 0                     NOT NULL,
  IND_FICHA_RETENCION  NUMBER(1)                DEFAULT 0                     NOT NULL,
  COD_SUC_PROSEGUR     VARCHAR2(3 BYTE),
  COD_PREFIJO          VARCHAR2(3 BYTE)         DEFAULT '000'                 NOT NULL,
  IND_OFICINA          NUMBER(1)                DEFAULT 0                     NOT NULL,
  COD_PREFIJO_MATRIZ   VARCHAR2(3 BYTE)         DEFAULT '000'                 NOT NULL
);


CREATE INDEX AK_GE_OFICINAS_COMUNA ON GE_OFICINAS
(COD_REGION, COD_PROVINCIA, COD_COMUNA);


CREATE INDEX AK_GE_OFICINAS_DIRECCION ON GE_OFICINAS
(COD_DIRECCION, COD_OFICINA);


CREATE UNIQUE INDEX PK_GE_OFICINAS ON GE_OFICINAS
(COD_OFICINA);



ALTER TABLE GE_OFICINAS ADD (
  CHECK ( IND_OFICINA  IN (0,1) ),
  CONSTRAINT PK_GE_OFICINAS
  PRIMARY KEY
  (COD_OFICINA)
  USING INDEX PK_GE_OFICINAS);

ALTER TABLE GE_OFICINAS ADD (
  CONSTRAINT FK_GEOFIC_GECOMUNA 
  FOREIGN KEY (COD_REGION, COD_PROVINCIA, COD_COMUNA) 
  REFERENCES GE_COMUNAS (COD_REGION,COD_PROVINCIA,COD_COMUNA)  DISABLE,
  CONSTRAINT FK_GEOFIC_GEDIRECC 
  FOREIGN KEY (COD_DIRECCION) 
  REFERENCES GE_DIRECCIONES (COD_DIRECCION)  DISABLE,
  CONSTRAINT FK_GEOFIC_GEPROVINC 
  FOREIGN KEY (COD_PROVINCIA, COD_REGION) 
  REFERENCES GE_PROVINCIAS (COD_PROVINCIA,COD_REGION)  DISABLE,
  CONSTRAINT FK_GEOFIC_GEREGION 
  FOREIGN KEY (COD_REGION) 
  REFERENCES GE_REGIONES (COD_REGION)  DISABLE);

  
---------------------------------------------------------

CREATE TABLE GE_CALCLIENTE
(
  COD_CALCLIEN  VARCHAR2(2 BYTE)                NOT NULL,
  DES_CALCLIEN  VARCHAR2(40 BYTE)               NOT NULL
);


CREATE UNIQUE INDEX PK_GE_CALCLIENTE ON GE_CALCLIENTE
(COD_CALCLIEN);



ALTER TABLE GE_CALCLIENTE ADD (
  CONSTRAINT PK_GE_CALCLIENTE
  PRIMARY KEY
  (COD_CALCLIEN)
  USING INDEX PK_GE_CALCLIENTE);

--------------------------------------------------------

CREATE TABLE GE_BANCOS
(
  COD_BANCO      VARCHAR2(15 BYTE)              NOT NULL,
  DES_BANCO      VARCHAR2(40 BYTE)              NOT NULL,
  COD_BCOI       NUMBER(1),
  IND_PAC        NUMBER(1)                      DEFAULT 0                     NOT NULL,
  COD_DICOM      VARCHAR2(3 BYTE),
  COD_BANCO_ON2  VARCHAR2(15 BYTE)              DEFAULT '1'                   NOT NULL
);


CREATE UNIQUE INDEX PK_GE_BANCOS ON GE_BANCOS
(COD_BANCO);


ALTER TABLE GE_BANCOS ADD (
  CONSTRAINT PK_GE_BANCOS
  PRIMARY KEY
  (COD_BANCO)
  USING INDEX PK_GE_BANCOS);

  
--------------------------------------------------------


CREATE TABLE GE_ACTIVIDADES
(
  COD_ACTIVIDAD  NUMBER(3)                      NOT NULL,
  DES_ACTIVIDAD  VARCHAR2(40 BYTE)              NOT NULL
);


CREATE UNIQUE INDEX PK_GE_ACTIVIDADES ON GE_ACTIVIDADES
(COD_ACTIVIDAD);



ALTER TABLE GE_ACTIVIDADES ADD (
  CONSTRAINT PK_GE_ACTIVIDADES
  PRIMARY KEY
  (COD_ACTIVIDAD)
  USING INDEX PK_GE_ACTIVIDADES);
 
--------------------------------------------------------

CREATE TABLE GA_CUENTAS
(
  COD_CUENTA          NUMBER(8)                 NOT NULL,
  DES_CUENTA          VARCHAR2(50 BYTE)         NOT NULL,
  TIP_CUENTA          VARCHAR2(1 BYTE)          NOT NULL,
  NOM_RESPONSABLE     VARCHAR2(50 BYTE)         NOT NULL,
  COD_TIPIDENT        VARCHAR2(2 BYTE)          NOT NULL,
  NUM_IDENT           VARCHAR2(20 BYTE)         NOT NULL,
  COD_DIRECCION       NUMBER(20)                NOT NULL,
  FEC_ALTA            DATE                      NOT NULL,
  IND_ESTADO          VARCHAR2(1 BYTE)          NOT NULL,
  TEL_CONTACTO        VARCHAR2(15 BYTE),
  IND_SECTOR          VARCHAR2(1 BYTE),
  COD_CLASCTA         VARCHAR2(2 BYTE),
  COD_CATRIBUT        CHAR(1 BYTE),
  COD_CATEGORIA       NUMBER(4),
  COD_SECTOR          NUMBER(4),
  COD_SUBCATEGORIA    VARCHAR2(5 BYTE),
  IND_MULTUSO         CHAR(1 BYTE)              DEFAULT 'N'                   NOT NULL,
  IND_CLIEPOTENCIAL   CHAR(1 BYTE)              DEFAULT 'N'                   NOT NULL,
  DES_RAZON_SOCIAL    VARCHAR2(50 BYTE),
  FEC_INIVTA_PAC      DATE,
  COD_TIPCOMIS        VARCHAR2(2 BYTE),
  NOM_USUARIO_ASESOR  VARCHAR2(30 BYTE),
  FEC_NACIMIENTO      DATE
);

COMMENT ON TABLE GA_CUENTAS IS 'Cuentas de Clientes';

COMMENT ON COLUMN GA_CUENTAS.COD_CUENTA IS 'Codigo de Cuenta';

COMMENT ON COLUMN GA_CUENTAS.DES_CUENTA IS 'Descripcion de Cuenta';

COMMENT ON COLUMN GA_CUENTAS.TIP_CUENTA IS 'Tipo de Cuenta (P)articular/(E)mpresa';

COMMENT ON COLUMN GA_CUENTAS.NOM_RESPONSABLE IS 'Nombre del Responsable';

COMMENT ON COLUMN GA_CUENTAS.COD_TIPIDENT IS 'Tipo de Identificacion';

COMMENT ON COLUMN GA_CUENTAS.NUM_IDENT IS 'Numero de Identificacion';

COMMENT ON COLUMN GA_CUENTAS.COD_DIRECCION IS 'Codigo de Direccion';

COMMENT ON COLUMN GA_CUENTAS.FEC_ALTA IS 'Fecha de Alta';

COMMENT ON COLUMN GA_CUENTAS.IND_ESTADO IS 'Indicativo de Estado (C)umplimentada/(S)in Cumplimentar';

COMMENT ON COLUMN GA_CUENTAS.TEL_CONTACTO IS 'Telefono de Contacto';

COMMENT ON COLUMN GA_CUENTAS.IND_SECTOR IS 'Indicativo de Sector (P)ublico/P(R)ivado';

COMMENT ON COLUMN GA_CUENTAS.COD_CLASCTA IS 'Codigo de Clasificacion de Cuenta';

COMMENT ON COLUMN GA_CUENTAS.COD_CATRIBUT IS 'Tipo de categoria tributaria de la cuenta';

COMMENT ON COLUMN GA_CUENTAS.COD_CATEGORIA IS 'Tipo de categoria de la cuenta';

COMMENT ON COLUMN GA_CUENTAS.COD_SECTOR IS 'Indicativo de Sector de la categoria';

COMMENT ON COLUMN GA_CUENTAS.COD_SUBCATEGORIA IS 'Subcategoria de la cuenta.';

COMMENT ON COLUMN GA_CUENTAS.IND_MULTUSO IS 'Indicador de Multiples usos.';

COMMENT ON COLUMN GA_CUENTAS.IND_CLIEPOTENCIAL IS 'Indicador de Cuenta Potencial.';

COMMENT ON COLUMN GA_CUENTAS.DES_RAZON_SOCIAL IS 'Razon social de la cuenta potencial.';

COMMENT ON COLUMN GA_CUENTAS.FEC_INIVTA_PAC IS 'Fecha de la primera venta PA en Cuotas del grupo .';

COMMENT ON COLUMN GA_CUENTAS.COD_TIPCOMIS IS 'codigo de comisionista de la primera venta.';

COMMENT ON COLUMN GA_CUENTAS.NOM_USUARIO_ASESOR IS 'NOMBRE USUARIO ASESOR DE LA CUENTA';

COMMENT ON COLUMN GA_CUENTAS.FEC_NACIMIENTO IS 'Fecha de nacimiento Persona Fisica o Moral';



CREATE INDEX AK_CUENTA_ASESOR ON GA_CUENTAS
(NOM_USUARIO_ASESOR);


CREATE INDEX AK_GA_CUENTAS_CATEGORIA ON GA_CUENTAS
(COD_CATEGORIA);


CREATE INDEX AK_GA_CUENTAS_NUMIDENT ON GA_CUENTAS
(NUM_IDENT);


CREATE INDEX AK_GA_CUENTAS_SUBCATEGORIA ON GA_CUENTAS
(COD_SUBCATEGORIA);


CREATE INDEX AK_GA_CUENTA_CLASCTA ON GA_CUENTAS
(COD_CLASCTA);


CREATE INDEX AK_GA_CUENTA_DIRECCION ON GA_CUENTAS
(COD_DIRECCION);


CREATE INDEX AK_GA_CUENTA_RESPONSABLE ON GA_CUENTAS
(NOM_RESPONSABLE);


CREATE INDEX GA_CUENTA_DESCUENTA_IE ON GA_CUENTAS
(DES_CUENTA);


CREATE INDEX GA_CUENTA_TELCONTACTO_IE ON GA_CUENTAS
(TEL_CONTACTO);


CREATE UNIQUE INDEX PK_GA_CUENTAS ON GA_CUENTAS
(COD_CUENTA);



ALTER TABLE GA_CUENTAS ADD (
  CONSTRAINT PK_GA_CUENTAS
  PRIMARY KEY
  (COD_CUENTA)
  USING INDEX PK_GA_CUENTAS);

ALTER TABLE GA_CUENTAS ADD (
  CONSTRAINT FK_CUENTA_CATEGORIA 
  FOREIGN KEY (COD_CATEGORIA) 
  REFERENCES GE_CATEGORIAS (COD_CATEGORIA)  DISABLE,
  CONSTRAINT FK_CUENTA_CLASCTA 
  FOREIGN KEY (COD_CLASCTA) 
  REFERENCES GE_CLASCTA (COD_CLASCTA)  DISABLE,
  CONSTRAINT FK_CUENTA_DIRECCION 
  FOREIGN KEY (COD_DIRECCION) 
  REFERENCES GE_DIRECCIONES (COD_DIRECCION)  DISABLE,
  CONSTRAINT FK_CUENTA_TIPIDENT 
  FOREIGN KEY (COD_TIPIDENT) 
  REFERENCES GE_TIPIDENT (COD_TIPIDENT)  DISABLE);

  
------------------------------------------------------------------


CREATE TABLE GE_ALMS
(
  COD_ALM            VARCHAR2(3 BYTE)           NOT NULL,
  DES_ALM            VARCHAR2(30 BYTE)          NOT NULL,
  COD_OPERADORA_SCL  VARCHAR2(5 BYTE),
  COD_TIPO_ALM       VARCHAR2(5 BYTE)
);


CREATE UNIQUE INDEX PK_GE_ALMS ON GE_ALMS
(COD_ALM);


ALTER TABLE GE_ALMS ADD (
  CONSTRAINT PK_GE_ALMS
  PRIMARY KEY
  (COD_ALM)
  USING INDEX PK_GE_ALMS);

ALTER TABLE GE_ALMS ADD (
  CONSTRAINT GE_ALMS_OPSC_FK 
  FOREIGN KEY (COD_OPERADORA_SCL) 
  REFERENCES GE_OPERADORA_SCL (COD_OPERADORA_SCL)  DISABLE);


------------------------------------------------------------------

CREATE TABLE GE_PRODUCTOS
(
  COD_PRODUCTO  NUMBER(1)                       NOT NULL,
  IND_REAL      NUMBER(1)                       NOT NULL,
  DES_PRODUCTO  VARCHAR2(20 BYTE)               NOT NULL
);


CREATE UNIQUE INDEX PK_GE_PRODUCTOS ON GE_PRODUCTOS
(COD_PRODUCTO)
;


ALTER TABLE GE_PRODUCTOS ADD (
  CONSTRAINT PK_GE_PRODUCTOS
  PRIMARY KEY
  (COD_PRODUCTO)
  USING INDEX PK_GE_PRODUCTOS);


--------------------------------------------------------------------

CREATE TABLE ICG_SISTEMA
(
  COD_SISTEMA   NUMBER(2)                       NOT NULL,
  COD_LENGUAJE  NUMBER(3)                       NOT NULL,
  COD_INTERFAZ  NUMBER(2)                       NOT NULL,
  COD_ESTADO    NUMBER(2)                       NOT NULL,
  IND_TIPO      NUMBER(1)                       NOT NULL,
  DES_SISTEMA   VARCHAR2(30 BYTE)               NOT NULL
);


CREATE INDEX FK_I_ICGSIS_ICGESC ON ICG_SISTEMA
(COD_ESTADO);


CREATE INDEX FK_I_ICGSIS_ICGINT ON ICG_SISTEMA
(COD_INTERFAZ);


CREATE INDEX FK_I_ICGSIS_ICGLEN ON ICG_SISTEMA
(COD_LENGUAJE);


CREATE UNIQUE INDEX PK_ICG_SISTEMA ON ICG_SISTEMA
(COD_SISTEMA, COD_LENGUAJE);


CREATE UNIQUE INDEX UK_ICG_SISTEMA ON ICG_SISTEMA
(COD_SISTEMA)
;


ALTER TABLE ICG_SISTEMA ADD (
  CONSTRAINT PK_ICG_SISTEMA
  PRIMARY KEY
  (COD_SISTEMA, COD_LENGUAJE)
  USING INDEX PK_ICG_SISTEMA,
  CONSTRAINT UK_ICG_SISTEMA
  UNIQUE (COD_SISTEMA)
  USING INDEX UK_ICG_SISTEMA);

ALTER TABLE ICG_SISTEMA ADD (
  CONSTRAINT FK_ICGSIS_ICGESC 
  FOREIGN KEY (COD_ESTADO) 
  REFERENCES ICG_ESTADO_CENTRAL (COD_ESTADO)  DISABLE,
  CONSTRAINT FK_ICGSIS_ICGINT 
  FOREIGN KEY (COD_INTERFAZ) 
  REFERENCES ICG_INTERFAZ (COD_INTERFAZ)  DISABLE,
  CONSTRAINT FK_ICGSIS_ICGLEN 
  FOREIGN KEY (COD_LENGUAJE) 
  REFERENCES ICG_LENGUAJE (COD_LENGUAJE)  DISABLE);



-------------------------------------------------------------------

CREATE TABLE ICG_CENTRAL
(
  COD_CENTRAL      NUMBER(3)                    NOT NULL,
  COD_PRODUCTO     NUMBER(1)                    NOT NULL,
  NOM_CENTRAL      VARCHAR2(15 BYTE)            NOT NULL,
  COD_NEMOTEC      VARCHAR2(15 BYTE)            NOT NULL,
  COD_ALM          VARCHAR2(3 BYTE)             NOT NULL,
  NUM_MAXINTENTOS  NUMBER(2)                    NOT NULL,
  COD_SISTEMA      NUMBER(2)                    NOT NULL,
  COD_COBERTURA    NUMBER(1)                    DEFAULT 1                     NOT NULL,
  TIE_RESPUESTA    NUMBER(12,4),
  NODOCOM          VARCHAR2(20 BYTE),
  COD_TECNOLOGIA   VARCHAR2(7 BYTE)             NOT NULL,
  COD_HLR          VARCHAR2(10 BYTE)
);


CREATE UNIQUE INDEX AK_ICG_CENTRAL ON ICG_CENTRAL
(COD_NEMOTEC);


CREATE INDEX FK_I_ICGEN_GEALMS ON ICG_CENTRAL
(COD_ALM);


CREATE INDEX FK_I_ICGEN_ICCEN ON ICG_CENTRAL
(COD_CENTRAL);


CREATE INDEX FK_I_ICGEN_ICGSIS ON ICG_CENTRAL
(COD_SISTEMA);


CREATE UNIQUE INDEX PK_ICG_CENTRAL ON ICG_CENTRAL
(COD_PRODUCTO, COD_CENTRAL);



ALTER TABLE ICG_CENTRAL ADD (
  CONSTRAINT PK_ICG_CENTRAL
  PRIMARY KEY
  (COD_PRODUCTO, COD_CENTRAL)
  USING INDEX PK_ICG_CENTRAL,
  CONSTRAINT AK_ICG_CENTRAL
  UNIQUE (COD_NEMOTEC)
  USING INDEX AK_ICG_CENTRAL);

ALTER TABLE ICG_CENTRAL ADD (
  CONSTRAINT FK_ICGCEN_GEALMS 
  FOREIGN KEY (COD_ALM) 
  REFERENCES GE_ALMS (COD_ALM)  DISABLE,
  CONSTRAINT FK_ICGCEN_GEPROD 
  FOREIGN KEY (COD_PRODUCTO) 
  REFERENCES GE_PRODUCTOS (COD_PRODUCTO)  DISABLE,
  CONSTRAINT FK_ICGCEN_ICGSIS 
  FOREIGN KEY (COD_SISTEMA) 
  REFERENCES ICG_SISTEMA (COD_SISTEMA)  DISABLE);

  
-----------------------------------------------------------

CREATE TABLE GE_MODVENTA
(
  COD_MODVENTA  NUMBER(2)                       NOT NULL,
  DES_MODVENTA  VARCHAR2(40 BYTE)               NOT NULL,
  IND_CUOTAS    NUMBER(1)                       NOT NULL,
  IND_PAGADO    NUMBER(1),
  COD_CAUPAGO   NUMBER(2),
  IND_ABONO     NUMBER(1),
  IND_SEGURO    NUMBER(1)                       DEFAULT 0                     NOT NULL
);


CREATE INDEX GEMODVENTA_CAUSAPAGO_IF ON GE_MODVENTA
(COD_CAUPAGO);


CREATE UNIQUE INDEX PK_GE_MODVENTA ON GE_MODVENTA
(COD_MODVENTA);


ALTER TABLE GE_MODVENTA ADD (
  CONSTRAINT PK_GE_MODVENTA
  PRIMARY KEY
  (COD_MODVENTA)
  USING INDEX PK_GE_MODVENTA);

ALTER TABLE GE_MODVENTA ADD (
  CONSTRAINT FK_GEMODVENTA_CAUSAPAGO 
  FOREIGN KEY (COD_CAUPAGO) 
  REFERENCES CO_CAUSASPAGO (COD_CAUPAGO)  DISABLE);

------------------------------------------------------------

CREATE TABLE GE_CLIENTES
(
  COD_CLIENTE             NUMBER(8)             NOT NULL,
  NOM_CLIENTE             VARCHAR2(50 BYTE)     NOT NULL,
  COD_TIPIDENT            VARCHAR2(2 BYTE)      NOT NULL,
  NUM_IDENT               VARCHAR2(20 BYTE)     NOT NULL,
  COD_CALCLIEN            VARCHAR2(2 BYTE)      NOT NULL,
  IND_SITUACION           VARCHAR2(2 BYTE)      NOT NULL,
  FEC_ALTA                DATE                  NOT NULL,
  IND_FACTUR              NUMBER(1)             NOT NULL,
  IND_TRASPASO            VARCHAR2(1 BYTE)      NOT NULL,
  IND_AGENTE              VARCHAR2(1 BYTE)      NOT NULL,
  FEC_ULTMOD              DATE                  NOT NULL,
  NUM_FAX                 VARCHAR2(15 BYTE),
  IND_MANDATO             NUMBER(1),
  NOM_USUARORA            VARCHAR2(30 BYTE)     NOT NULL,
  IND_ALTA                VARCHAR2(1 BYTE)      NOT NULL,
  COD_CUENTA              NUMBER(8)             NOT NULL,
  IND_ACEPVENT            VARCHAR2(1 BYTE)      NOT NULL,
  COD_ABC                 VARCHAR2(1 BYTE)      NOT NULL,
  COD_123                 NUMBER(1)             NOT NULL,
  COD_ACTIVIDAD           NUMBER(3),
  COD_PAIS                VARCHAR2(3 BYTE),
  TEF_CLIENTE1            VARCHAR2(15 BYTE),
  NUM_ABOCEL              NUMBER(4),
  TEF_CLIENTE2            VARCHAR2(15 BYTE),
  NUM_ABOBEEP             NUMBER(4),
  IND_DEBITO              VARCHAR2(1 BYTE),
  NUM_ABOTRUNK            NUMBER(4),
  COD_PROSPECTO           NUMBER(8),
  NUM_ABOTREK             NUMBER(4),
  COD_SISPAGO             NUMBER(2),
  NOM_APECLIEN1           VARCHAR2(20 BYTE),
  NOM_EMAIL               VARCHAR2(255 BYTE),
  NUM_ABORENT             NUMBER(4),
  NOM_APECLIEN2           VARCHAR2(20 BYTE),
  NUM_ABOROAMING          NUMBER(4),
  FEC_ACEPVENT            DATE,
  IMP_STOPDEBIT           NUMBER(12,4),
  COD_BANCO               VARCHAR2(15 BYTE),
  COD_SUCURSAL            VARCHAR2(4 BYTE),
  IND_TIPCUENTA           VARCHAR2(1 BYTE),
  COD_TIPTARJETA          VARCHAR2(3 BYTE),
  NUM_CTACORR             VARCHAR2(18 BYTE),
  NUM_TARJETA             VARCHAR2(18 BYTE),
  FEC_VENCITARJ           DATE,
  COD_BANCOTARJ           VARCHAR2(15 BYTE),
  COD_TIPIDTRIB           VARCHAR2(2 BYTE),
  NUM_IDENTTRIB           VARCHAR2(20 BYTE),
  COD_TIPIDENTAPOR        VARCHAR2(2 BYTE),
  NUM_IDENTAPOR           VARCHAR2(20 BYTE),
  NOM_APODERADO           VARCHAR2(40 BYTE),
  COD_OFICINA             VARCHAR2(2 BYTE),
  FEC_BAJA                DATE,
  COD_COBRADOR            NUMBER(6),
  COD_PINCLI              VARCHAR2(4 BYTE),
  COD_CICLO               NUMBER(2),
  NUM_CELULAR             NUMBER(15),
  IND_TIPPERSONA          VARCHAR2(1 BYTE)      DEFAULT 'F',
  COD_CICLONUE            NUMBER(2),
  COD_CATEGORIA           NUMBER(4),
  COD_SECTOR              NUMBER(4),
  COD_SUPERVISOR          NUMBER(6),
  IND_ESTCIVIL            CHAR(1 BYTE),
  FEC_NACIMIEN            DATE,
  IND_SEXO                CHAR(1 BYTE),
  NUM_INT_GRUP_FAM        NUMBER(2),
  COD_NPI                 NUMBER(2),
  COD_SUBCATEGORIA        VARCHAR2(5 BYTE),
  COD_USO                 VARCHAR2(5 BYTE),
  COD_IDIOMA              VARCHAR2(5 BYTE)      DEFAULT '1'                   NOT NULL,
  COD_TIPIDENT2           VARCHAR2(2 BYTE),
  NUM_IDENT2              VARCHAR2(20 BYTE),
  NOM_USUARIO_ASESOR      VARCHAR2(30 BYTE),
  COD_OPERADORA           VARCHAR2(5 BYTE)      DEFAULT 'TMG'                 NOT NULL,
  IND_FACTURAELECTRONICA  NUMBER(1)             DEFAULT 0                     NOT NULL,
  NOM_CONYUGE             VARCHAR2(50 BYTE),
  COD_OPERADOR            NUMBER(5),
  MENS_PROMO              VARCHAR2(1 BYTE)      DEFAULT 'A',
  COD_PROFESION           NUMBER(3),
  NOM_EMPRESA             VARCHAR2(50 BYTE),
  TEF_OFICINA             VARCHAR2(15 BYTE),
  COD_OCUPACION           VARCHAR2(3 BYTE),
  IMP_INGRESOS            NUMBER(14,4),
  NOM_JEFE                VARCHAR2(50 BYTE),
  CANT_ANLABOR            VARCHAR2(2 BYTE),
  NOM_REFER1              VARCHAR2(50 BYTE),
  TEF_REFER1              VARCHAR2(15 BYTE),
  NOM_REFER2              VARCHAR2(50 BYTE),
  COD_TIPO                VARCHAR2(5 BYTE)      DEFAULT 3,
  COD_COLOR               VARCHAR2(5 BYTE)      DEFAULT 10,
  COD_CREDITICIA          VARCHAR2(5 BYTE)      DEFAULT 'EXC',
  COD_SEGMENTO            VARCHAR2(5 BYTE)      DEFAULT 1,
  COD_CALIFICACION        VARCHAR2(5 BYTE)      DEFAULT 'A',
  NOM_TITULARTARJETA      VARCHAR2(50 BYTE),
  OBS_PAC                 VARCHAR2(100 BYTE),
  TEF_REFER2              VARCHAR2(15 BYTE)
);

COMMENT ON TABLE GE_CLIENTES IS 'Clientes del sistema.';

COMMENT ON COLUMN GE_CLIENTES.COD_CLIENTE IS 'Codigo Cliente';

COMMENT ON COLUMN GE_CLIENTES.NOM_CLIENTE IS 'Nombre Cliente';

COMMENT ON COLUMN GE_CLIENTES.COD_TIPIDENT IS 'Tipo Identificacion Cliente';

COMMENT ON COLUMN GE_CLIENTES.NUM_IDENT IS 'Numero Identificacion Cliente';

COMMENT ON COLUMN GE_CLIENTES.COD_CALCLIEN IS 'Codigo Calidad Cliente';

COMMENT ON COLUMN GE_CLIENTES.IND_SITUACION IS 'Situacion Cliente; (S)in Cumplimentar, (C)umplimentado';

COMMENT ON COLUMN GE_CLIENTES.FEC_ALTA IS 'Fecha de Alta';

COMMENT ON COLUMN GE_CLIENTES.IND_FACTUR IS 'Indicativo de Facturable ; Si(1), No(0)';

COMMENT ON COLUMN GE_CLIENTES.IND_TRASPASO IS 'Indicativo de Traspasos ; Si(S), No(N)';

COMMENT ON COLUMN GE_CLIENTES.IND_AGENTE IS 'Indicativo de Agente ; Si(S), No(N)';

COMMENT ON COLUMN GE_CLIENTES.FEC_ULTMOD IS 'Fecha Ultima Modificacion Cliente';

COMMENT ON COLUMN GE_CLIENTES.NUM_FAX IS 'Numero de Fax del Cliente';

COMMENT ON COLUMN GE_CLIENTES.IND_MANDATO IS 'Indicativo Mandato Domiciliacion ; Si (0), No (1)';

COMMENT ON COLUMN GE_CLIENTES.NOM_USUARORA IS 'Usuario Creador Cliente';

COMMENT ON COLUMN GE_CLIENTES.IND_ALTA IS 'Indicador Procedencia de Alta ; Venta (V) Traspaso (T) Agente (A) Roaming (R) Rent a Phone (P)';

COMMENT ON COLUMN GE_CLIENTES.COD_CUENTA IS 'Codigo Cuenta Cliente';

COMMENT ON COLUMN GE_CLIENTES.IND_ACEPVENT IS 'Indicativo Aceptacion Venta ; Si(1), No(0)';

COMMENT ON COLUMN GE_CLIENTES.COD_ABC IS 'Codigo Clasificacion ABC';

COMMENT ON COLUMN GE_CLIENTES.COD_123 IS 'Codigo Clasificacion 123';

COMMENT ON COLUMN GE_CLIENTES.COD_ACTIVIDAD IS 'Codigo Actividad';

COMMENT ON COLUMN GE_CLIENTES.COD_PAIS IS 'Codigo del pais';

COMMENT ON COLUMN GE_CLIENTES.TEF_CLIENTE1 IS 'Telefono Contacto Cliente';

COMMENT ON COLUMN GE_CLIENTES.NUM_ABOCEL IS 'Numero Abonados Celular';

COMMENT ON COLUMN GE_CLIENTES.TEF_CLIENTE2 IS 'Telefono Contacto Cliente';

COMMENT ON COLUMN GE_CLIENTES.NUM_ABOBEEP IS 'Numero Abonados Beeper';

COMMENT ON COLUMN GE_CLIENTES.IND_DEBITO IS 'Indicativo Debito ; Automatico (A), Manual (M)';

COMMENT ON COLUMN GE_CLIENTES.NUM_ABOTRUNK IS 'Numero Abonados Trunking';

COMMENT ON COLUMN GE_CLIENTES.COD_PROSPECTO IS 'Codigo de Prospecto Origen';

COMMENT ON COLUMN GE_CLIENTES.NUM_ABOTREK IS 'Numero Abonados Trek';

COMMENT ON COLUMN GE_CLIENTES.COD_SISPAGO IS 'Sistema de pago';

COMMENT ON COLUMN GE_CLIENTES.NOM_APECLIEN1 IS 'Primer Apellido Cliente';

COMMENT ON COLUMN GE_CLIENTES.NOM_EMAIL IS 'Direccion E-Mail del Cliente';

COMMENT ON COLUMN GE_CLIENTES.NUM_ABORENT IS 'Numero Abonados Rent a Phone';

COMMENT ON COLUMN GE_CLIENTES.NOM_APECLIEN2 IS 'Segundo Apellido Cliente';

COMMENT ON COLUMN GE_CLIENTES.NUM_ABOROAMING IS 'Numero Abonados Roaming';

COMMENT ON COLUMN GE_CLIENTES.FEC_ACEPVENT IS 'Fecha de aceptacion de la venta';

COMMENT ON COLUMN GE_CLIENTES.IMP_STOPDEBIT IS 'Importe Limite Debito';

COMMENT ON COLUMN GE_CLIENTES.COD_BANCO IS 'Codigo de Banco';

COMMENT ON COLUMN GE_CLIENTES.COD_SUCURSAL IS 'Codigo de Sucursal';

COMMENT ON COLUMN GE_CLIENTES.IND_TIPCUENTA IS 'Indicativo Tipo Cuenta ; Corriente (C), Ahorro (A)';

COMMENT ON COLUMN GE_CLIENTES.COD_TIPTARJETA IS 'Codigo Tipo Tarjeta';

COMMENT ON COLUMN GE_CLIENTES.NUM_CTACORR IS 'Numero cuenta corriente';

COMMENT ON COLUMN GE_CLIENTES.NUM_TARJETA IS 'Numero de tarjeta';

COMMENT ON COLUMN GE_CLIENTES.FEC_VENCITARJ IS 'Fecha vencimiento de la tarjeta';

COMMENT ON COLUMN GE_CLIENTES.COD_BANCOTARJ IS 'Codigo banco tarjeta';

COMMENT ON COLUMN GE_CLIENTES.COD_TIPIDTRIB IS 'Codigo Tipo Identificacion Tributaria';

COMMENT ON COLUMN GE_CLIENTES.NUM_IDENTTRIB IS 'Numero Identificacion Tributaria';

COMMENT ON COLUMN GE_CLIENTES.COD_TIPIDENTAPOR IS 'Codigo Tipo Identificacion Apoderado';

COMMENT ON COLUMN GE_CLIENTES.NUM_IDENTAPOR IS 'Numero identificador del apoderado';

COMMENT ON COLUMN GE_CLIENTES.NOM_APODERADO IS 'Nombre del apoderado';

COMMENT ON COLUMN GE_CLIENTES.COD_OFICINA IS 'Codigo de oficina';

COMMENT ON COLUMN GE_CLIENTES.FEC_BAJA IS 'Fecha de baja';

COMMENT ON COLUMN GE_CLIENTES.COD_COBRADOR IS 'Codigo de cobrador';

COMMENT ON COLUMN GE_CLIENTES.COD_PINCLI IS 'Codigo de identificacion del cliente';

COMMENT ON COLUMN GE_CLIENTES.COD_CICLONUE IS 'Indicador, si el cliente tiene pendiente un cambio de ciclo';

COMMENT ON COLUMN GE_CLIENTES.COD_CATEGORIA IS 'Codigo Categoria de Cliente.';

COMMENT ON COLUMN GE_CLIENTES.COD_SECTOR IS 'Codigo Sector Publico o Privado.';

COMMENT ON COLUMN GE_CLIENTES.COD_SUPERVISOR IS 'Codigo Supervisor.';

COMMENT ON COLUMN GE_CLIENTES.IND_ESTCIVIL IS 'Estado civil del usuario: C=Casado | S=Soltero | D=Divorciado | V=Viudo | O=Otro';

COMMENT ON COLUMN GE_CLIENTES.FEC_NACIMIEN IS 'Fecha nacimiento del cliente.';

COMMENT ON COLUMN GE_CLIENTES.IND_SEXO IS 'Sexo del cliente: M=Masculino | F=Femenino.';

COMMENT ON COLUMN GE_CLIENTES.NUM_INT_GRUP_FAM IS 'Numero de integrantes del grupo familiar';

COMMENT ON COLUMN GE_CLIENTES.COD_NPI IS 'Indicador de Privacidad; 0:Sin Privaci
dad, 1: Con Privacidad';

COMMENT ON COLUMN GE_CLIENTES.COD_SUBCATEGORIA IS 'Subcategoria del cliente.';

COMMENT ON COLUMN GE_CLIENTES.COD_USO IS 'Codigo del uso de la cuenta.';

COMMENT ON COLUMN GE_CLIENTES.COD_IDIOMA IS 'Idioma del Cliente.';

COMMENT ON COLUMN GE_CLIENTES.COD_TIPIDENT2 IS 'Codigo de Tipo de Idioma Opcional.';

COMMENT ON COLUMN GE_CLIENTES.NUM_IDENT2 IS 'Numero de Identificacion Opcional.';

COMMENT ON COLUMN GE_CLIENTES.NOM_USUARIO_ASESOR IS 'NOMBRE USUARIO ASESOR DEL CLIENTE';

COMMENT ON COLUMN GE_CLIENTES.COD_OPERADORA IS 'Codigo de Operadora del Cliente.';

COMMENT ON COLUMN GE_CLIENTES.NOM_CONYUGE IS 'Nombre conyuge';

COMMENT ON COLUMN GE_CLIENTES.COD_OPERADOR IS 'Operadora Anterior';

COMMENT ON COLUMN GE_CLIENTES.MENS_PROMO IS 'Desea recibir mensajes promocionales';

COMMENT ON COLUMN GE_CLIENTES.COD_PROFESION IS 'Profesion';

COMMENT ON COLUMN GE_CLIENTES.NOM_EMPRESA IS 'Nombre Empresa';

COMMENT ON COLUMN GE_CLIENTES.TEF_OFICINA IS 'Telefono Oficina';

COMMENT ON COLUMN GE_CLIENTES.COD_OCUPACION IS 'Cargo';

COMMENT ON COLUMN GE_CLIENTES.IMP_INGRESOS IS 'Ingresos Mensuales';

COMMENT ON COLUMN GE_CLIENTES.NOM_JEFE IS 'Jefe Inmediato';

COMMENT ON COLUMN GE_CLIENTES.CANT_ANLABOR IS 'A?os Laborando';

COMMENT ON COLUMN GE_CLIENTES.NOM_REFER1 IS 'Nombre Referencia I';

COMMENT ON COLUMN GE_CLIENTES.TEF_REFER1 IS 'Telefono';

COMMENT ON COLUMN GE_CLIENTES.NOM_REFER2 IS 'Nombre Referencia II';

COMMENT ON COLUMN GE_CLIENTES.COD_TIPO IS 'Tipo cliente';

COMMENT ON COLUMN GE_CLIENTES.COD_COLOR IS 'Color';

COMMENT ON COLUMN GE_CLIENTES.COD_CREDITICIA IS 'Crediticia';

COMMENT ON COLUMN GE_CLIENTES.COD_SEGMENTO IS 'Categoria de Cobros CAMPO YA EXISTE';

COMMENT ON COLUMN GE_CLIENTES.COD_CALIFICACION IS 'Segmento';

COMMENT ON COLUMN GE_CLIENTES.NOM_TITULARTARJETA IS 'Calificacion';

COMMENT ON COLUMN GE_CLIENTES.OBS_PAC IS 'Titular tarjeta';

COMMENT ON COLUMN GE_CLIENTES.TEF_REFER2 IS 'Telefono';



CREATE INDEX AK_CLIENTE_ASESOR_USO ON GE_CLIENTES
(NOM_USUARIO_ASESOR, COD_USO);


CREATE INDEX AK_GECLIENTES_CELULAR ON GE_CLIENTES
(NUM_CELULAR);

CREATE INDEX AK_GE_CLIENTES_ACTIVIDADES ON GE_CLIENTES
(COD_ACTIVIDAD);


CREATE INDEX AK_GE_CLIENTES_BANCOS ON GE_CLIENTES
(COD_BANCOTARJ);


CREATE INDEX AK_GE_CLIENTES_CALCLIENTE ON GE_CLIENTES
(COD_CALCLIEN);


CREATE INDEX AK_GE_CLIENTES_CATEGORIA ON GE_CLIENTES
(COD_CATEGORIA);


CREATE INDEX AK_GE_CLIENTES_COBRADOR ON GE_CLIENTES
(COD_COBRADOR);


CREATE INDEX AK_GE_CLIENTES_OFICINAS ON GE_CLIENTES
(COD_OFICINA);


CREATE INDEX AK_GE_CLIENTES_PAISES ON GE_CLIENTES
(COD_PAIS);


CREATE INDEX AK_GE_CLIENTES_SISPAGO ON GE_CLIENTES
(COD_SISPAGO);


CREATE INDEX AK_GE_CLIENTES_SUBCATEGORIA ON GE_CLIENTES
(COD_SUBCATEGORIA);


CREATE INDEX AK_GE_CLIENTES_SUCURSALES ON GE_CLIENTES
(COD_BANCO, COD_SUCURSAL);


CREATE INDEX AK_GE_CLIENTES_TIPIDENTAPOR ON GE_CLIENTES
(COD_TIPIDENTAPOR);


CREATE INDEX AK_GE_CLIENTES_TIPIDTRIB ON GE_CLIENTES
(COD_TIPIDTRIB);


CREATE INDEX AK_GE_CLIENTES_TIPTARJETA ON GE_CLIENTES
(COD_TIPTARJETA);


CREATE INDEX AK_GE_CLIENTES_USARORA ON GE_CLIENTES
(NOM_USUARORA);


CREATE INDEX AK_GE_CLIENTE_CUENTA ON GE_CLIENTES
(COD_CUENTA);


CREATE INDEX AK_GE_CLIENTE_IDENTIFICACION ON GE_CLIENTES
(COD_TIPIDENT, NUM_IDENT);


CREATE INDEX AK_GE_CLIENTE_NOMCLI ON GE_CLIENTES
(NOM_CLIENTE);


CREATE UNIQUE INDEX PK_GE_CLIENTES ON GE_CLIENTES
(COD_CLIENTE);



CREATE OR REPLACE PUBLIC SYNONYM GE_CLIENTES FOR GE_CLIENTES;


ALTER TABLE GE_CLIENTES ADD (
  CONSTRAINT PK_GE_CLIENTES
  PRIMARY KEY
  (COD_CLIENTE)
  USING INDEX PK_GE_CLIENTES);

ALTER TABLE GE_CLIENTES ADD (
  CONSTRAINT FK_CLIENTES_123 
  FOREIGN KEY (COD_123) 
  REFERENCES CO_123 (COD_123)  DISABLE,
  CONSTRAINT FK_CLIENTES_ABC 
  FOREIGN KEY (COD_ABC) 
  REFERENCES CO_ABC (COD_ABC)  DISABLE,
  CONSTRAINT FK_CLIENTES_ACTIVIDADES 
  FOREIGN KEY (COD_ACTIVIDAD) 
  REFERENCES GE_ACTIVIDADES (COD_ACTIVIDAD)  DISABLE,
  CONSTRAINT FK_CLIENTES_BANCOS 
  FOREIGN KEY (COD_BANCOTARJ) 
  REFERENCES GE_BANCOS (COD_BANCO)  DISABLE,
  CONSTRAINT FK_CLIENTES_CALCLIENTE 
  FOREIGN KEY (COD_CALCLIEN) 
  REFERENCES GE_CALCLIENTE (COD_CALCLIEN)  DISABLE,
  CONSTRAINT FK_CLIENTES_CATEGORIA 
  FOREIGN KEY (COD_CATEGORIA) 
  REFERENCES GE_CATEGORIAS (COD_CATEGORIA)  DISABLE,
  CONSTRAINT FK_CLIENTES_COBRADORES 
  FOREIGN KEY (COD_COBRADOR) 
  REFERENCES CO_COBRADOR (COD_COBRADOR)  DISABLE,
  CONSTRAINT FK_CLIENTES_OFICINAS 
  FOREIGN KEY (COD_OFICINA) 
  REFERENCES GE_OFICINAS (COD_OFICINA)  DISABLE,
  CONSTRAINT FK_CLIENTES_PAISES 
  FOREIGN KEY (COD_PAIS) 
  REFERENCES GE_PAISES (COD_PAIS)  DISABLE,
  CONSTRAINT FK_CLIENTES_SISPAGO 
  FOREIGN KEY (COD_SISPAGO) 
  REFERENCES GE_SISPAGO (COD_SISPAGO)  DISABLE,
  CONSTRAINT FK_CLIENTES_SUCURSALES 
  FOREIGN KEY (COD_BANCO, COD_SUCURSAL) 
  REFERENCES GE_SUCURSALES (COD_BANCO,COD_SUCURSAL)  DISABLE,
  CONSTRAINT FK_CLIENTES_TIPIDENT 
  FOREIGN KEY (COD_TIPIDENT) 
  REFERENCES GE_TIPIDENT (COD_TIPIDENT)  DISABLE,
  CONSTRAINT FK_CLIENTES_TIPIDENTAPOR 
  FOREIGN KEY (COD_TIPIDENTAPOR) 
  REFERENCES GE_TIPIDENT (COD_TIPIDENT)  DISABLE,
  CONSTRAINT FK_CLIENTES_TIPIDTRIB 
  FOREIGN KEY (COD_TIPIDTRIB) 
  REFERENCES GE_TIPIDENT (COD_TIPIDENT)  DISABLE,
  CONSTRAINT FK_CLIENTES_TIPTARJETAS 
  FOREIGN KEY (COD_TIPTARJETA) 
  REFERENCES GE_TIPTARJETAS (COD_TIPTARJETA)  DISABLE,
  CONSTRAINT FK_CLIENTES_USARORA 
  FOREIGN KEY (NOM_USUARORA) 
  REFERENCES GE_SEG_USUARIO (NOM_USUARIO)  DISABLE);


------------------------------------------------------------


CREATE TABLE GE_CELDAS
(
  COD_CELDA    VARCHAR2(7 BYTE)                 NOT NULL,
  COD_SUBALM   VARCHAR2(5 BYTE)                 NOT NULL,
  DES_CELDA    VARCHAR2(50 BYTE)                NOT NULL,
  COD_SUBALM2  VARCHAR2(5 BYTE)
);

CREATE INDEX AK_CELDAS_SUBALM ON GE_CELDAS
(COD_SUBALM);


CREATE UNIQUE INDEX PK_GE_CELDAS ON GE_CELDAS
(COD_CELDA);

ALTER TABLE GE_CELDAS ADD (
  CONSTRAINT PK_GE_CELDAS
  PRIMARY KEY
  (COD_CELDA)
  USING INDEX PK_GE_CELDAS);

ALTER TABLE GE_CELDAS ADD (
  CONSTRAINT FK_CELDA_SUBALM 
  FOREIGN KEY (COD_SUBALM) 
  REFERENCES GE_SUBALMS (COD_SUBALM)  DISABLE);

------------------------------------------------------------

CREATE TABLE GA_TIPCONTRATO
(
  COD_PRODUCTO     NUMBER(1)                    NOT NULL,
  COD_TIPCONTRATO  VARCHAR2(3 BYTE)             NOT NULL,
  DES_TIPCONTRATO  VARCHAR2(30 BYTE)            NOT NULL,
  FEC_DESDE        DATE                         NOT NULL,
  FEC_HASTA        DATE,
  IND_CONTSEG      VARCHAR2(3 BYTE),
  IND_CONTCEL      VARCHAR2(1 BYTE),
  IND_COMODATO     NUMBER(1),
  CANAL_VTA        NUMBER(1),
  MESES_MINIMO     NUMBER(2),
  IND_PROCEQUI     VARCHAR2(1 BYTE)             DEFAULT 'I'                   NOT NULL,
  IND_PRECIOLISTA  VARCHAR2(1 BYTE)             DEFAULT '1'                   NOT NULL,
  IND_GMC          VARCHAR2(3 BYTE)             DEFAULT '0'                   NOT NULL
);


CREATE UNIQUE INDEX PK_GA_TIPCONTRATO ON GA_TIPCONTRATO
(COD_PRODUCTO, COD_TIPCONTRATO);


ALTER TABLE GA_TIPCONTRATO ADD (
  CONSTRAINT PK_GA_TIPCONTRATO
  PRIMARY KEY
  (COD_PRODUCTO, COD_TIPCONTRATO)
  USING INDEX PK_GA_TIPCONTRATO);

ALTER TABLE GA_TIPCONTRATO ADD (
  CONSTRAINT FK_TIPCONTRATO_PRODUCTO 
  FOREIGN KEY (COD_PRODUCTO) 
  REFERENCES GE_PRODUCTOS (COD_PRODUCTO)  DISABLE);

  
------------------------------------------------------------------


CREATE TABLE GA_PLANSERV
(
  COD_PRODUCTO  NUMBER(1)                       NOT NULL,
  COD_PLANSERV  VARCHAR2(3 BYTE)                NOT NULL,
  DES_PLANSERV  VARCHAR2(30 BYTE)               NOT NULL,
  FEC_DESDE     DATE                            NOT NULL,
  FEC_HASTA     DATE
);


CREATE UNIQUE INDEX PK_GA_PLANSERV ON GA_PLANSERV
(COD_PRODUCTO, COD_PLANSERV);


ALTER TABLE GA_PLANSERV ADD (
  CONSTRAINT PK_GA_PLANSERV
  PRIMARY KEY
  (COD_PRODUCTO, COD_PLANSERV)
  USING INDEX PK_GA_PLANSERV);

ALTER TABLE GA_PLANSERV ADD (
  CONSTRAINT FK_PLANSERV_PRODUCTO 
  FOREIGN KEY (COD_PRODUCTO) 
  REFERENCES GE_PRODUCTOS (COD_PRODUCTO)  DISABLE);

  
--------------------------------------------------------

CREATE TABLE FA_CICLOS
(
  COD_CICLO  NUMBER(2)                          NOT NULL,
  DES_CICLO  VARCHAR2(40 BYTE)                  NOT NULL,
  DIG_D      NUMBER(1)                          NOT NULL,
  DIG_C      NUMBER(1)                          NOT NULL,
  DIG_SEC    NUMBER(6)                          DEFAULT 0                     NOT NULL
);


CREATE UNIQUE INDEX PK_FA_CICLOS ON FA_CICLOS
(COD_CICLO);

ALTER TABLE FA_CICLOS ADD (
  CONSTRAINT PK_FA_CICLOS
  PRIMARY KEY
  (COD_CICLO)
  USING INDEX PK_FA_CICLOS);

  
----------------------------------------------------------

CREATE TABLE GA_ABOCEL
(
  NUM_ABONADO            NUMBER(8)              NOT NULL,
  NUM_CELULAR            NUMBER(15)             NOT NULL,
  COD_PRODUCTO           NUMBER(1)              DEFAULT 1                     NOT NULL,
  COD_CLIENTE            NUMBER(8)              NOT NULL,
  COD_CUENTA             NUMBER(8)              NOT NULL,
  COD_SUBCUENTA          VARCHAR2(15 BYTE)      NOT NULL,
  COD_USUARIO            NUMBER(8)              NOT NULL,
  COD_REGION             VARCHAR2(3 BYTE)       NOT NULL,
  COD_PROVINCIA          VARCHAR2(5 BYTE)       NOT NULL,
  COD_CIUDAD             VARCHAR2(5 BYTE)       NOT NULL,
  COD_CELDA              VARCHAR2(7 BYTE)       NOT NULL,
  COD_CENTRAL            NUMBER(3)              NOT NULL,
  COD_USO                NUMBER(2)              NOT NULL,
  COD_SITUACION          VARCHAR2(3 BYTE)       NOT NULL,
  IND_PROCALTA           VARCHAR2(1 BYTE)       NOT NULL,
  IND_PROCEQUI           VARCHAR2(2 BYTE)       NOT NULL,
  COD_VENDEDOR           NUMBER(6)              NOT NULL,
  COD_VENDEDOR_AGENTE    NUMBER(6)              NOT NULL,
  TIP_PLANTARIF          VARCHAR2(1 BYTE)       NOT NULL,
  TIP_TERMINAL           VARCHAR2(1 BYTE)       NOT NULL,
  COD_PLANTARIF          VARCHAR2(3 BYTE)       NOT NULL,
  COD_CARGOBASICO        VARCHAR2(3 BYTE)       NOT NULL,
  COD_PLANSERV           VARCHAR2(3 BYTE)       NOT NULL,
  COD_LIMCONSUMO         VARCHAR2(5 BYTE),
  NUM_SERIE              VARCHAR2(25 BYTE)      NOT NULL,
  NUM_SERIEHEX           VARCHAR2(8 BYTE)       NOT NULL,
  NOM_USUARORA           VARCHAR2(30 BYTE)      NOT NULL,
  FEC_ALTA               DATE                   NOT NULL,
  NUM_PERCONTRATO        NUMBER(2)              DEFAULT 1                     NOT NULL,
  COD_ESTADO             VARCHAR2(2 BYTE)       NOT NULL,
  NUM_SERIEMEC           VARCHAR2(20 BYTE),
  COD_HOLDING            NUMBER(8),
  COD_EMPRESA            NUMBER(8),
  COD_GRPSERV            VARCHAR2(2 BYTE),
  IND_SUPERTEL           NUMBER(1),
  NUM_TELEFIJA           VARCHAR2(15 BYTE),
  COD_OPREDFIJA          NUMBER(5),
  COD_CARRIER            NUMBER(5),
  IND_PREPAGO            NUMBER(1),
  IND_PLEXSYS            NUMBER(1),
  COD_CENTRAL_PLEX       NUMBER(3),
  NUM_CELULAR_PLEX       NUMBER(15),
  NUM_VENTA              NUMBER(8),
  COD_MODVENTA           NUMBER(2),
  COD_TIPCONTRATO        VARCHAR2(3 BYTE),
  NUM_CONTRATO           VARCHAR2(21 BYTE),
  NUM_ANEXO              VARCHAR2(21 BYTE),
  FEC_CUMPLAN            DATE,
  COD_CREDMOR            NUMBER(3),
  COD_CREDCON            NUMBER(3),
  COD_CICLO              NUMBER(2),
  IND_FACTUR             NUMBER(1),
  IND_SUSPEN             NUMBER(1),
  IND_REHABI             NUMBER(1),
  IND_INSGUIAS           NUMBER(1),
  FEC_FINCONTRA          DATE,
  FEC_RECDOCUM           DATE,
  FEC_CUMPLIMEN          DATE,
  FEC_ACEPVENTA          DATE,
  FEC_ACTCEN             DATE,
  FEC_BAJA               DATE,
  FEC_BAJACEN            DATE,
  FEC_ULTMOD             DATE,
  COD_CAUSABAJA          VARCHAR2(2 BYTE),
  NUM_PERSONAL           VARCHAR2(4 BYTE),
  IND_SEGURO             NUMBER(1),
  CLASE_SERVICIO         VARCHAR2(255 BYTE),
  PERFIL_ABONADO         VARCHAR2(255 BYTE),
  NUM_MIN                VARCHAR2(3 BYTE)       DEFAULT '730',
  COD_VENDEALER          NUMBER(6),
  IND_DISP               NUMBER(1),
  COD_PASSWORD           VARCHAR2(7 BYTE),
  IND_PASSWORD           CHAR(1 BYTE),
  COD_AFINIDAD           NUMBER(3),
  FEC_PRORROGA           DATE,
  IND_EQPRESTADO         VARCHAR2(1 BYTE),
  FLG_CONTDIGI           CHAR(1 BYTE),
  FEC_ALTANTRAS          DATE,
  COD_INDEMNIZACION      NUMBER(3),
  NUM_IMEI               VARCHAR2(25 BYTE),
  COD_TECNOLOGIA         VARCHAR2(7 BYTE),
  NUM_MIN_MDN            VARCHAR2(10 BYTE),
  FEC_ACTIVACION         DATE,
  IND_TELEFONO           NUMBER(1)              DEFAULT 6                     NOT NULL,
  COD_OFICINA_PRINCIPAL  VARCHAR2(2 BYTE),
  COD_CAUSA_VENTA        VARCHAR2(5 BYTE),
  COD_OPERACION          VARCHAR2(5 BYTE),
  COD_PRESTACION         VARCHAR2(5 BYTE),
  MTO_VALOR_REFERENCIA   NUMBER(14,4),
  COD_MONEDA             VARCHAR2(3 BYTE),
  TIPO_PRIMARIACARRIER   VARCHAR2(3 BYTE),
  OBS_INSTANCIA          VARCHAR2(50 BYTE)
);

COMMENT ON TABLE GA_ABOCEL IS 'Abonados Red Celular';

COMMENT ON COLUMN GA_ABOCEL.NUM_ABONADO IS 'Secuencia Numero Abonado';

COMMENT ON COLUMN GA_ABOCEL.NUM_CELULAR IS 'Numero de Celular';

COMMENT ON COLUMN GA_ABOCEL.COD_PRODUCTO IS 'Tipo de Producto';

COMMENT ON COLUMN GA_ABOCEL.COD_CLIENTE IS 'Codigo de Cliente';

COMMENT ON COLUMN GA_ABOCEL.COD_CUENTA IS 'Codigo de Cuenta';

COMMENT ON COLUMN GA_ABOCEL.COD_SUBCUENTA IS 'Codigo de Subcuenta';

COMMENT ON COLUMN GA_ABOCEL.COD_USUARIO IS 'Codigo de Usuario Producto';

COMMENT ON COLUMN GA_ABOCEL.COD_REGION IS 'Codigo de Region';

COMMENT ON COLUMN GA_ABOCEL.COD_PROVINCIA IS 'Codigo de Provincia';

COMMENT ON COLUMN GA_ABOCEL.COD_CIUDAD IS 'Codigo de Ciudad';

COMMENT ON COLUMN GA_ABOCEL.COD_CELDA IS 'Codigo de Celda';

COMMENT ON COLUMN GA_ABOCEL.COD_CENTRAL IS 'Codigo de Central';

COMMENT ON COLUMN GA_ABOCEL.COD_USO IS 'Codigo de Uso de Numeracion';

COMMENT ON COLUMN GA_ABOCEL.COD_SITUACION IS 'Codigo de Situacion de Abonado';

COMMENT ON COLUMN GA_ABOCEL.IND_PROCALTA IS 'Indicativo de Procedencia Alta ; Interna (I), Externa (E)';

COMMENT ON COLUMN GA_ABOCEL.IND_PROCEQUI IS 'Indicativo de Procedencia Equipo ; Interno (I), Externo (E), Subsidiado (S)';

COMMENT ON COLUMN GA_ABOCEL.COD_VENDEDOR IS 'Codigo de Vendedor';

COMMENT ON COLUMN GA_ABOCEL.COD_VENDEDOR_AGENTE IS 'Codigo de Agente';

COMMENT ON COLUMN GA_ABOCEL.TIP_PLANTARIF IS 'Tipo de Plan Tarifario ; Individual (I), Empresa (E), Holding (H)';

COMMENT ON COLUMN GA_ABOCEL.TIP_TERMINAL IS 'Tipo de Terminal ; Analogico (A), Digital (D)';

COMMENT ON COLUMN GA_ABOCEL.COD_PLANTARIF IS 'Codigo de Plan Tarifario';

COMMENT ON COLUMN GA_ABOCEL.COD_CARGOBASICO IS 'Codigo Cargo Basico';

COMMENT ON COLUMN GA_ABOCEL.COD_PLANSERV IS 'Codigo de Plan de Servicios';

COMMENT ON COLUMN GA_ABOCEL.COD_LIMCONSUMO IS 'Codigo de Limite de Consumo';

COMMENT ON COLUMN GA_ABOCEL.NUM_SERIE IS 'Numero de Serie Decimal';

COMMENT ON COLUMN GA_ABOCEL.NUM_SERIEHEX IS 'Numero de Serie Hexadecimal';

COMMENT ON COLUMN GA_ABOCEL.NOM_USUARORA IS 'Usuario Creador Abonado';

COMMENT ON COLUMN GA_ABOCEL.FEC_ALTA IS 'Fecha de Alta Abonado';

COMMENT ON COLUMN GA_ABOCEL.NUM_PERCONTRATO IS 'Numero del Periodo de Contrato';

COMMENT ON COLUMN GA_ABOCEL.COD_ESTADO IS 'Estado en Cartera de Cobros';

COMMENT ON COLUMN GA_ABOCEL.NUM_SERIEMEC IS 'Numero de Serie Mecanico';

COMMENT ON COLUMN GA_ABOCEL.COD_HOLDING IS 'Holding en el cual se encuentra incluido el abonado';

COMMENT ON COLUMN GA_ABOCEL.COD_EMPRESA IS 'Empresa en la cual se encuentra incluido el abonado';

COMMENT ON COLUMN GA_ABOCEL.COD_GRPSERV IS 'Grupo de Cobro de Servicios en el cual se encuentra incluido el abonado';

COMMENT ON COLUMN GA_ABOCEL.IND_SUPERTEL IS 'Indicativo Modalidad Supertelefono ; No (0), Si (1)';

COMMENT ON COLUMN GA_ABOCEL.NUM_TELEFIJA IS 'Numero de telefonia Fija';

COMMENT ON COLUMN GA_ABOCEL.COD_OPREDFIJA IS 'Operador de Red Fija';

COMMENT ON COLUMN GA_ABOCEL.COD_CARRIER IS 'Operador de Carrie';

COMMENT ON COLUMN GA_ABOCEL.IND_PREPAGO IS 'Indicasivo de Prepago No(0), Si(1)';

COMMENT ON COLUMN GA_ABOCEL.IND_PLEXSYS IS 'Indicativo Abonado Zona Plexsys; No (0), Si (1)';

COMMENT ON COLUMN GA_ABOCEL.COD_CENTRAL_PLEX IS 'Codigo Segunda Central Abonados Plexsys';

COMMENT ON COLUMN GA_ABOCEL.NUM_CELULAR_PLEX IS 'Segundo Numero de Celular Plexsys';

COMMENT ON COLUMN GA_ABOCEL.NUM_VENTA IS 'Numero de Venta';

COMMENT ON COLUMN GA_ABOCEL.COD_MODVENTA IS 'Codigo de Modalidad de Venta';

COMMENT ON COLUMN GA_ABOCEL.COD_TIPCONTRATO IS 'Tipo de Contrato Venta';

COMMENT ON COLUMN GA_ABOCEL.NUM_CONTRATO IS 'Numero de Contrato';

COMMENT ON COLUMN GA_ABOCEL.NUM_ANEXO IS 'Numero de Anexo Contrato';

COMMENT ON COLUMN GA_ABOCEL.FEC_CUMPLAN IS 'Fecha Posible Cambio Plan Tarifario';

COMMENT ON COLUMN GA_ABOCEL.COD_CREDMOR IS 'Codigo de Limite Credito de Morosidad';

COMMENT ON COLUMN GA_ABOCEL.COD_CREDCON IS 'Codigo de Limite Credito de Consumo';

COMMENT ON COLUMN GA_ABOCEL.COD_CICLO IS 'Codigo de Ciclo Facturacion';

COMMENT ON COLUMN GA_ABOCEL.IND_FACTUR IS 'Indicativo de Facturable ; No (0), Si (1)';

COMMENT ON COLUMN GA_ABOCEL.IND_SUSPEN IS 'Indicativo de Suspendible ; No (0), Si (1)';

COMMENT ON COLUMN GA_ABOCEL.IND_REHABI IS 'Indicativo de Rehabilitable ; No (0), Si (1)';

COMMENT ON COLUMN GA_ABOCEL.IND_INSGUIAS IS 'Indicativo de Insercion en Guias ; No (0), Si (1)';

COMMENT ON COLUMN GA_ABOCEL.FEC_FINCONTRA IS 'Fecha de Fin Contrato';

COMMENT ON COLUMN GA_ABOCEL.FEC_RECDOCUM IS 'Fecha de Recepcion Documentacion';

COMMENT ON COLUMN GA_ABOCEL.FEC_CUMPLIMEN IS 'Fecha de Cumplimentacion Datos';

COMMENT ON COLUMN GA_ABOCEL.FEC_ACEPVENTA IS 'Fecha de Aceptacion Venta';

COMMENT ON COLUMN GA_ABOCEL.FEC_ACTCEN IS 'Fecha de Activacion en Central';

COMMENT ON COLUMN GA_ABOCEL.FEC_BAJA IS 'Fecha de Baja';

COMMENT ON COLUMN GA_ABOCEL.FEC_BAJACEN IS 'Fecha de Baja en Central';

COMMENT ON COLUMN GA_ABOCEL.FEC_ULTMOD IS 'Fecha de Ultima Modificacion';

COMMENT ON COLUMN GA_ABOCEL.COD_CAUSABAJA IS 'Codigo de Causa de Baja';

COMMENT ON COLUMN GA_ABOCEL.NUM_PERSONAL IS 'Codigo de Bloqueo de Terminal';

COMMENT ON COLUMN GA_ABOCEL.IND_SEGURO IS 'Indicativo de Seguro ; Si (0), No (1)';

COMMENT ON COLUMN GA_ABOCEL.CLASE_SERVICIO IS 'Matricula de Servicios contratados por el Abonado';

COMMENT ON COLUMN GA_ABOCEL.PERFIL_ABONADO IS 'Matricula de Servicios Activos del Abonado';

COMMENT ON COLUMN GA_ABOCEL.NUM_MIN IS 'Prefijo MIN';

COMMENT ON COLUMN GA_ABOCEL.IND_DISP IS 'Indicativo de Disponibilidad 0:No disponible (STP) 1:Disponible';

COMMENT ON COLUMN GA_ABOCEL.COD_PASSWORD IS 'Password de acceso via Internet.';

COMMENT ON COLUMN GA_ABOCEL.IND_PASSWORD IS 'Indicador de validez de password: 0=valida | 1=invalida.';

COMMENT ON COLUMN GA_ABOCEL.COD_AFINIDAD IS 'Codigo de afinidad';

COMMENT ON COLUMN GA_ABOCEL.FEC_PRORROGA IS 'Fecha de Prorroga de Contrato';

COMMENT ON COLUMN GA_ABOCEL.IND_EQPRESTADO IS 'Indicador de equipo prestado';

COMMENT ON COLUMN GA_ABOCEL.FLG_CONTDIGI IS 'Indica si el contrato esta digitalizado.';

COMMENT ON COLUMN GA_ABOCEL.FEC_ALTANTRAS IS 'Indica la fecha de alta anterior, dado que se hizo un traspaso..';

COMMENT ON COLUMN GA_ABOCEL.NUM_IMEI IS 'Numero Serie Terminal GSM';

COMMENT ON COLUMN GA_ABOCEL.COD_TECNOLOGIA IS 'Codigo Tecnologia';

COMMENT ON COLUMN GA_ABOCEL.NUM_MIN_MDN IS 'MIN asociado al Numero Celular (funcion logistica).';

COMMENT ON COLUMN GA_ABOCEL.COD_OFICINA_PRINCIPAL IS 'Codigo Oficina Principal';

COMMENT ON COLUMN GA_ABOCEL.COD_CAUSA_VENTA IS 'Codigo de Causa deVenta';

COMMENT ON COLUMN GA_ABOCEL.COD_OPERACION IS 'Codigo de Operacion';

COMMENT ON COLUMN GA_ABOCEL.COD_PRESTACION IS 'Prestacion de la linea, ver GE_PRESTACIONES_TD';

COMMENT ON COLUMN GA_ABOCEL.MTO_VALOR_REFERENCIA IS 'Valor de Referencia por minuto';

COMMENT ON COLUMN GA_ABOCEL.COD_MONEDA IS 'moneda del valor de referencia del minuto';

COMMENT ON COLUMN GA_ABOCEL.TIPO_PRIMARIACARRIER IS 'Tipologia Primaria (servicio 144) carrier';

COMMENT ON COLUMN GA_ABOCEL.OBS_INSTANCIA IS 'observacion de instancia';



CREATE INDEX ABOCEL_CIUDADES_IF ON GA_ABOCEL
(COD_REGION, COD_PROVINCIA, COD_CIUDAD);


CREATE INDEX AK_GA_ABOCEL_CAUSABAJA ON GA_ABOCEL
(COD_PRODUCTO, COD_CAUSABAJA);


CREATE INDEX AK_GA_ABOCEL_CELDAS ON GA_ABOCEL
(COD_CELDA);


CREATE INDEX AK_GA_ABOCEL_CENTPLEX ON GA_ABOCEL
(COD_PRODUCTO, COD_CENTRAL_PLEX);


CREATE INDEX AK_GA_ABOCEL_CENTRALES ON GA_ABOCEL
(COD_PRODUCTO, COD_CENTRAL);


CREATE INDEX AK_GA_ABOCEL_CICLOS ON GA_ABOCEL
(COD_CICLO);


CREATE INDEX AK_GA_ABOCEL_CLIENTE ON GA_ABOCEL
(COD_CLIENTE);


CREATE INDEX AK_GA_ABOCEL_CUENTAS ON GA_ABOCEL
(COD_CUENTA, COD_SITUACION);


CREATE INDEX AK_GA_ABOCEL_EMPRESA ON GA_ABOCEL
(COD_EMPRESA);


CREATE INDEX AK_GA_ABOCEL_ESTADOS ON GA_ABOCEL
(COD_ESTADO);


CREATE INDEX AK_GA_ABOCEL_GRPSERV ON GA_ABOCEL
(COD_PRODUCTO, COD_GRPSERV);


CREATE INDEX AK_GA_ABOCEL_HOLDING ON GA_ABOCEL
(COD_HOLDING);


CREATE INDEX AK_GA_ABOCEL_LIMCONSUMO ON GA_ABOCEL
(COD_PRODUCTO, COD_LIMCONSUMO);


CREATE INDEX AK_GA_ABOCEL_LIMCONSUMOCOB ON GA_ABOCEL
(COD_CREDCON, COD_PRODUCTO);


CREATE INDEX AK_GA_ABOCEL_LIMCREDITO ON GA_ABOCEL
(COD_CREDMOR, COD_PRODUCTO);


CREATE INDEX AK_GA_ABOCEL_MODVENTA ON GA_ABOCEL
(COD_MODVENTA)
;


CREATE INDEX AK_GA_ABOCEL_NUMCELULAR ON GA_ABOCEL
(NUM_CELULAR);


CREATE INDEX AK_GA_ABOCEL_NUMSERIE ON GA_ABOCEL
(NUM_SERIE);


CREATE INDEX AK_GA_ABOCEL_OPCARRIER ON GA_ABOCEL
(COD_CARRIER);


CREATE INDEX AK_GA_ABOCEL_OPREDFIJA ON GA_ABOCEL
(COD_OPREDFIJA);


CREATE INDEX AK_GA_ABOCEL_PLANSERV ON GA_ABOCEL
(COD_PRODUCTO, COD_PLANSERV);


CREATE INDEX AK_GA_ABOCEL_PLANTARIF ON GA_ABOCEL
(COD_PRODUCTO, COD_PLANTARIF);


CREATE INDEX AK_GA_ABOCEL_SITUABO ON GA_ABOCEL
(COD_SITUACION);


CREATE INDEX AK_GA_ABOCEL_SUBCUENTAS ON GA_ABOCEL
(COD_SUBCUENTA);


CREATE INDEX AK_GA_ABOCEL_TIPCONTRATO ON GA_ABOCEL
(COD_PRODUCTO, COD_TIPCONTRATO);


CREATE INDEX AK_GA_ABOCEL_TIPTERMINAL ON GA_ABOCEL
(COD_PRODUCTO, TIP_TERMINAL);


CREATE INDEX AK_GA_ABOCEL_USOS ON GA_ABOCEL
(COD_USO);


CREATE INDEX AK_GA_ABOCEL_USUARIO ON GA_ABOCEL
(COD_USUARIO);


CREATE INDEX AK_GA_ABOCEL_VENTAS ON GA_ABOCEL
(NUM_VENTA);


CREATE INDEX GA_ABOCEL_NUM_IMEI_IE ON GA_ABOCEL
(NUM_IMEI);


CREATE INDEX GA_ABOC_CAUSAVENTA_IF ON GA_ABOCEL
(COD_OPERACION, COD_CAUSA_VENTA);


CREATE INDEX NUK_GA_ABOCEL_PASSWORD_TMC ON GA_ABOCEL
(COD_PASSWORD);


CREATE UNIQUE INDEX PK_GA_ABOCEL ON GA_ABOCEL
(NUM_ABONADO);



ALTER TABLE GA_ABOCEL ADD (
  CONSTRAINT PK_GA_ABOCEL
  PRIMARY KEY
  (NUM_ABONADO)
  USING INDEX PK_GA_ABOCEL);

ALTER TABLE GA_ABOCEL ADD (
  CONSTRAINT FK_ABOCEL_CAUSABAJA 
  FOREIGN KEY (COD_PRODUCTO, COD_CAUSABAJA) 
  REFERENCES GA_CAUSABAJA (COD_PRODUCTO,COD_CAUSABAJA)  DISABLE,
  CONSTRAINT FK_ABOCEL_CELDAS 
  FOREIGN KEY (COD_CELDA) 
  REFERENCES GE_CELDAS (COD_CELDA)  DISABLE,
  CONSTRAINT FK_ABOCEL_CENTPLEX 
  FOREIGN KEY (COD_PRODUCTO, COD_CENTRAL_PLEX) 
  REFERENCES ICG_CENTRAL (COD_PRODUCTO,COD_CENTRAL)  DISABLE,
  CONSTRAINT FK_ABOCEL_CENTRALES 
  FOREIGN KEY (COD_PRODUCTO, COD_CENTRAL) 
  REFERENCES ICG_CENTRAL (COD_PRODUCTO,COD_CENTRAL)  DISABLE,
  CONSTRAINT FK_ABOCEL_CICLOS 
  FOREIGN KEY (COD_CICLO) 
  REFERENCES FA_CICLOS (COD_CICLO)  DISABLE,
  CONSTRAINT FK_ABOCEL_CLIENTES 
  FOREIGN KEY (COD_CLIENTE) 
  REFERENCES GE_CLIENTES (COD_CLIENTE)  DISABLE,
  CONSTRAINT FK_ABOCEL_EMPRESA 
  FOREIGN KEY (COD_EMPRESA) 
  REFERENCES GA_EMPRESA (COD_EMPRESA)  DISABLE,
  CONSTRAINT FK_ABOCEL_ESTADOS 
  FOREIGN KEY (COD_ESTADO) 
  REFERENCES CO_ESTADOS (COD_ESTADO)  DISABLE,
  CONSTRAINT FK_ABOCEL_GRPSERV 
  FOREIGN KEY (COD_PRODUCTO, COD_GRPSERV) 
  REFERENCES GA_GRPSERV (COD_PRODUCTO,COD_GRUPO)  DISABLE,
  CONSTRAINT FK_ABOCEL_HOLDING 
  FOREIGN KEY (COD_HOLDING) 
  REFERENCES GA_HOLDING (COD_HOLDING)  DISABLE,
  CONSTRAINT FK_ABOCEL_LIMCONSUMOCOB 
  FOREIGN KEY (COD_CREDCON, COD_PRODUCTO) 
  REFERENCES CO_LIMCONSUMO (COD_CREDCON,COD_PRODUCTO)  DISABLE,
  CONSTRAINT FK_ABOCEL_LIMCREDITO 
  FOREIGN KEY (COD_CREDMOR, COD_PRODUCTO) 
  REFERENCES CO_LIMCREDITOS (COD_CREDMOR,COD_PRODUCTO)  DISABLE,
  CONSTRAINT FK_ABOCEL_MODVENTA 
  FOREIGN KEY (COD_MODVENTA) 
  REFERENCES GE_MODVENTA (COD_MODVENTA)  DISABLE,
  CONSTRAINT FK_ABOCEL_OPCARRIER 
  FOREIGN KEY (COD_CARRIER) 
  REFERENCES TA_OPERADORES (COD_OPERADOR)  DISABLE,
  CONSTRAINT FK_ABOCEL_OPREDFIJA 
  FOREIGN KEY (COD_OPREDFIJA) 
  REFERENCES TA_OPERADORES (COD_OPERADOR)  DISABLE,
  CONSTRAINT FK_ABOCEL_PLANSERV 
  FOREIGN KEY (COD_PRODUCTO, COD_PLANSERV) 
  REFERENCES GA_PLANSERV (COD_PRODUCTO,COD_PLANSERV)  DISABLE,
  CONSTRAINT FK_ABOCEL_PRODUCTOS 
  FOREIGN KEY (COD_PRODUCTO) 
  REFERENCES GE_PRODUCTOS (COD_PRODUCTO)  DISABLE,
  CONSTRAINT FK_ABOCEL_SITUABO 
  FOREIGN KEY (COD_SITUACION) 
  REFERENCES GA_SITUABO (COD_SITUACION)  DISABLE,
  CONSTRAINT FK_ABOCEL_TECNOLOGIA 
  FOREIGN KEY (COD_TECNOLOGIA) 
  REFERENCES AL_TECNOLOGIA (COD_TECNOLOGIA)  DISABLE,
  CONSTRAINT FK_ABOCEL_TIPCONTRATO 
  FOREIGN KEY (COD_PRODUCTO, COD_TIPCONTRATO) 
  REFERENCES GA_TIPCONTRATO (COD_PRODUCTO,COD_TIPCONTRATO)  DISABLE,
  CONSTRAINT FK_ABOCEL_TIPTERMINAL 
  FOREIGN KEY (COD_PRODUCTO, TIP_TERMINAL) 
  REFERENCES AL_TIPOS_TERMINALES (COD_PRODUCTO,TIP_TERMINAL)  DISABLE,
  CONSTRAINT FK_ABOCEL_USOS 
  FOREIGN KEY (COD_USO) 
  REFERENCES AL_USOS (COD_USO)  DISABLE,
  CONSTRAINT GA_ABOCEL_CAUSAVENTA_FK 
  FOREIGN KEY (COD_OPERACION, COD_CAUSA_VENTA) 
  REFERENCES GA_OPERACIONES_CAUSAS_VENTA_TD (COD_OPERACION,COD_CAUSA_VENTA)  DISABLE,
  CONSTRAINT VE_OFIC_ABOC_OFIPPAL_FK 
  FOREIGN KEY (COD_OFICINA_PRINCIPAL) 
  REFERENCES GE_OFICINAS (COD_OFICINA)  DISABLE);


-----------------------------------------------

CREATE TABLE ICG_NIVELSERVICIO
(
  COD_PRODUCTO  NUMBER(1)                       NOT NULL,
  COD_SERVICIO  NUMBER(2)                       NOT NULL,
  COD_NIVEL     NUMBER(4)                       NOT NULL,
  DES_NIVEL     VARCHAR2(50 BYTE)               NOT NULL
);


CREATE UNIQUE INDEX PK_ICG_NIVELSERVICIO ON ICG_NIVELSERVICIO
(COD_PRODUCTO, COD_SERVICIO, COD_NIVEL);


ALTER TABLE ICG_NIVELSERVICIO ADD (
  CONSTRAINT PK_ICG_NIVELSERVICIO
  PRIMARY KEY
  (COD_PRODUCTO, COD_SERVICIO, COD_NIVEL)
  USING INDEX PK_ICG_NIVELSERVICIO);

ALTER TABLE ICG_NIVELSERVICIO ADD (
  CONSTRAINT FK_ICGNIV_ICGSER 
  FOREIGN KEY (COD_PRODUCTO, COD_SERVICIO) 
  REFERENCES ICG_SERVICIO (COD_PRODUCTO,COD_SERVICIO)  DISABLE);


-------------------------------------------------------------------

CREATE TABLE GA_SERVSUPL
(
  COD_PRODUCTO      NUMBER(1)                   NOT NULL,
  COD_SERVICIO      VARCHAR2(3 BYTE)            NOT NULL,
  COD_SERVSUPL      NUMBER(2)                   NOT NULL,
  COD_NIVEL         NUMBER(4)                   NOT NULL,
  DES_SERVICIO      VARCHAR2(40 BYTE)           NOT NULL,
  IND_AUTMAN        VARCHAR2(1 BYTE)            NOT NULL,
  IND_COMERC        NUMBER(1)                   DEFAULT 1                     NOT NULL,
  IND_PRO           NUMBER(1)                   DEFAULT 1                     NOT NULL,
  IND_CENTRAL       NUMBER(1),
  COD_APLIC         VARCHAR2(180 BYTE),
  IND_TRASPASO      NUMBER(1)                   DEFAULT 0,
  DES_SERVICIO_WEB  VARCHAR2(80 BYTE),
  IND_GESTOR        NUMBER(1)                   DEFAULT 0,
  IND_COBRO         NUMBER(2)                   DEFAULT 0,
  IND_PRIORIDAD     NUMBER(1)                   DEFAULT 3                     NOT NULL,
  TIP_SERVICIO      VARCHAR2(5 BYTE)            DEFAULT '1'                   NOT NULL,
  IND_TUXEDO        NUMBER(1)                   DEFAULT 0,
  IND_INFRANET      NUMBER(1)                   DEFAULT 0,
  SUB_CATEGORIA     VARCHAR2(10 BYTE),
  TIP_RED           VARCHAR2(1 BYTE)            DEFAULT 'M'                   NOT NULL,
  IND_IP            NUMBER(1)                   DEFAULT '0',
  TIP_COBRO         VARCHAR2(1 BYTE)            DEFAULT 'V',
  IND_COBRETR       NUMBER(1)                   DEFAULT 0,
  IND_RESTRINGIBLE  NUMBER(1)                   DEFAULT '0'
);


CREATE INDEX AK_GA_SERVSUPL_NIVELSERVICIO ON GA_SERVSUPL
(COD_PRODUCTO, COD_SERVSUPL, COD_NIVEL);


CREATE UNIQUE INDEX PK_GA_SERVSUPL ON GA_SERVSUPL
(COD_PRODUCTO, COD_SERVICIO);


ALTER TABLE GA_SERVSUPL ADD (
  CHECK ( IND_INFRANET IN (0,1) ),
  CONSTRAINT PK_GA_SERVSUPL
  PRIMARY KEY
  (COD_PRODUCTO, COD_SERVICIO)
  USING INDEX PK_GA_SERVSUPL);

ALTER TABLE GA_SERVSUPL ADD (
  CONSTRAINT FK_SERVSUPL_NIVELSERVICIO 
  FOREIGN KEY (COD_PRODUCTO, COD_SERVSUPL, COD_NIVEL) 
  REFERENCES ICG_NIVELSERVICIO (COD_PRODUCTO,COD_SERVICIO,COD_NIVEL)  DISABLE);


------------------------------------

CREATE TABLE GA_SERVSUPLABO
(
  NUM_ABONADO    NUMBER(8)                      NOT NULL,
  COD_SERVICIO   VARCHAR2(3 BYTE)               NOT NULL,
  FEC_ALTABD     DATE                           NOT NULL,
  COD_SERVSUPL   NUMBER(2)                      NOT NULL,
  COD_NIVEL      NUMBER(4)                      NOT NULL,
  COD_PRODUCTO   NUMBER(1)                      NOT NULL,
  NUM_TERMINAL   VARCHAR2(15 BYTE)              NOT NULL,
  NOM_USUARORA   VARCHAR2(30 BYTE)              NOT NULL,
  IND_ESTADO     NUMBER(1)                      DEFAULT 1                     NOT NULL,
  FEC_ALTACEN    DATE,
  FEC_BAJABD     DATE,
  FEC_BAJACEN    DATE,
  COD_CONCEPTO   NUMBER(4),
  NUM_DIASNUM    NUMBER(9),
  COD_PRIORIDAD  NUMBER(4),
  IND_DESBORDE   VARCHAR2(3 BYTE)
);

COMMENT ON TABLE GA_SERVSUPLABO IS 'Servicios Suplementarios de Abonados';

COMMENT ON COLUMN GA_SERVSUPLABO.NUM_ABONADO IS 'Numero de Abonado/Producto';

COMMENT ON COLUMN GA_SERVSUPLABO.COD_SERVICIO IS 'Codigo de Servicio';

COMMENT ON COLUMN GA_SERVSUPLABO.FEC_ALTABD IS 'Fecha de Alta en Base de Datos';

COMMENT ON COLUMN GA_SERVSUPLABO.COD_SERVSUPL IS 'Codigo de Servicio Suplementario';

COMMENT ON COLUMN GA_SERVSUPLABO.COD_NIVEL IS 'Nivel de Servicio Suplementario';

COMMENT ON COLUMN GA_SERVSUPLABO.COD_PRODUCTO IS 'Codigo de Producto';

COMMENT ON COLUMN GA_SERVSUPLABO.NUM_TERMINAL IS 'Numero de Terminal (Identificador Producto)';

COMMENT ON COLUMN GA_SERVSUPLABO.NOM_USUARORA IS 'Nombre de Usuario';

COMMENT ON COLUMN GA_SERVSUPLABO.IND_ESTADO IS 'Indicativo de Estado del Servicio; (1) Alta B.D., (2) Alta Central, (3) Baja B.D., (4) Baja Central';

COMMENT ON COLUMN GA_SERVSUPLABO.FEC_ALTACEN IS 'Fecha de Alta en Central';

COMMENT ON COLUMN GA_SERVSUPLABO.FEC_BAJABD IS 'Fecha de Baja en Base de Datos';

COMMENT ON COLUMN GA_SERVSUPLABO.FEC_BAJACEN IS 'Fecha de Baja en Central';

COMMENT ON COLUMN GA_SERVSUPLABO.COD_CONCEPTO IS 'Concepto de Facturacion Asociado';

COMMENT ON COLUMN GA_SERVSUPLABO.NUM_DIASNUM IS 'Numero de asociacion con dias especiales o friends and family';

COMMENT ON COLUMN GA_SERVSUPLABO.COD_PRIORIDAD IS 'Prioridad entre Servicios Suplementarios';

COMMENT ON COLUMN GA_SERVSUPLABO.IND_DESBORDE IS 'Indicador de desborde de aplicacion del SS al consumir sus unidades libres: DPT desborda hacia el Plan Tarifario,  DSS hacia otro Servicios Suplementarios y ND no Desborda';

CREATE INDEX AK_GA_SERVSUPLABO_CONCEPTOS ON GA_SERVSUPLABO
(COD_CONCEPTO);


CREATE INDEX AK_GA_SERVSUPLABO_SERVSUPL ON GA_SERVSUPLABO
(COD_PRODUCTO, COD_SERVICIO);


CREATE INDEX AK_GA_SERVSUPLABO_USUARORA ON GA_SERVSUPLABO
(NOM_USUARORA);


CREATE INDEX GA_SERVSUPLABO_SERVGRUPO_IE ON GA_SERVSUPLABO
(COD_SERVICIO, COD_SERVSUPL, IND_ESTADO);


CREATE UNIQUE INDEX PK_GA_SERVSUPLABO ON GA_SERVSUPLABO
(NUM_ABONADO, COD_SERVICIO, FEC_ALTABD);



ALTER TABLE GA_SERVSUPLABO ADD (
  CONSTRAINT PK_GA_SERVSUPLABO
  PRIMARY KEY
  (NUM_ABONADO, COD_SERVICIO, FEC_ALTABD)
  USING INDEX PK_GA_SERVSUPLABO);

  
--------------------------------------------
  
  
CREATE TABLE GA_INTARCEL
(
  COD_CLIENTE      NUMBER(8)                    NOT NULL,
  NUM_ABONADO      NUMBER(8)                    NOT NULL,
  IND_NUMERO       NUMBER(1)                    DEFAULT 1                     NOT NULL,
  FEC_DESDE        DATE                         NOT NULL,
  FEC_HASTA        DATE                         NOT NULL,
  IMP_LIMCONSUMO   NUMBER(14,4)                 NOT NULL,
  IND_FRIENDS      NUMBER(1)                    NOT NULL,
  IND_DIASESP      NUMBER(1)                    NOT NULL,
  COD_CELDA        VARCHAR2(7 BYTE)             NOT NULL,
  TIP_PLANTARIF    VARCHAR2(1 BYTE)             NOT NULL,
  COD_PLANTARIF    VARCHAR2(3 BYTE)             NOT NULL,
  NUM_SERIE        VARCHAR2(25 BYTE)            NOT NULL,
  NUM_CELULAR      NUMBER(15)                   NOT NULL,
  COD_CARGOBASICO  VARCHAR2(3 BYTE)             NOT NULL,
  COD_CICLO        NUMBER(2)                    NOT NULL,
  COD_PLANCOM      NUMBER(6)                    NOT NULL,
  COD_PLANSERV     VARCHAR2(3 BYTE)             NOT NULL,
  COD_GRPSERV      VARCHAR2(2 BYTE)             NOT NULL,
  COD_GRUPO        NUMBER(8),
  COD_PORTADOR     NUMBER(5),
  COD_USO          NUMBER(2)                    DEFAULT 4                     NOT NULL,
  NUM_IMSI         VARCHAR2(25 BYTE),
  NUM_MIN_MDN      VARCHAR2(15 BYTE)
);

COMMENT ON COLUMN GA_INTARCEL.COD_USO IS 'Codigo de uso.';

COMMENT ON COLUMN GA_INTARCEL.NUM_IMSI IS 'IMSI asociado a la SIMCARD';

COMMENT ON COLUMN GA_INTARCEL.NUM_MIN_MDN IS 'Min asociado al numero de celular';



CREATE INDEX AK1_GA_INTARCEL ON GA_INTARCEL
(NUM_IMSI);


CREATE INDEX AK_GA_INTARCEL ON GA_INTARCEL
(NUM_CELULAR, FEC_DESDE);


CREATE INDEX GA_INTARCEL_IDX_004 ON GA_INTARCEL
(COD_CLIENTE, NUM_ABONADO, FEC_DESDE, FEC_HASTA, NUM_CELULAR, 
NUM_SERIE);


CREATE UNIQUE INDEX PK_GA_INTARCEL ON GA_INTARCEL
(COD_CLIENTE, NUM_ABONADO, IND_NUMERO, FEC_DESDE);



ALTER TABLE GA_INTARCEL ADD (
  CONSTRAINT PK_GA_INTARCEL
  PRIMARY KEY
  (COD_CLIENTE, NUM_ABONADO, IND_NUMERO, FEC_DESDE)
  USING INDEX PK_GA_INTARCEL);

--------------------------------------------------

CREATE TABLE CI_TIPORSERV
(
  COD_OS           VARCHAR2(5 BYTE)             NOT NULL,
  DESCRIPCION      VARCHAR2(50 BYTE)            NOT NULL,
  COD_TIPMODI      VARCHAR2(2 BYTE)             NOT NULL,
  GRUPO            VARCHAR2(1 BYTE)             NOT NULL,
  NOM_EXE          VARCHAR2(30 BYTE)            NOT NULL,
  CARTA            VARCHAR2(255 BYTE)           NOT NULL,
  IND_PRORROGA     NUMBER(1)                    NOT NULL,
  MENU             VARCHAR2(14 BYTE)            NOT NULL,
  TIP_EXTENCION    VARCHAR2(3 BYTE)             DEFAULT 'EXE'                 NOT NULL,
  TIP_PROCESA      NUMBER(2),
  COD_APLIC        VARCHAR2(3 BYTE)             DEFAULT 'PVA'                 NOT NULL,
  COD_MODGENER     VARCHAR2(3 BYTE)             DEFAULT 'PXX'                 NOT NULL,
  IND_CRON         NUMBER(1),
  IND_ARCHIVO      NUMBER(2),
  IND_ALGUNOS      NUMBER(2),
  FEC_MIGRACION    DATE,
  PRG              VARCHAR2(60 BYTE)            DEFAULT 'X'                   NOT NULL,
  IND_CSERVICIO    VARCHAR2(60 BYTE)            DEFAULT '0'                   NOT NULL,
  IND_LOCK         NUMBER(2)                    DEFAULT 0                     NOT NULL,
  TIP_PROCESA_FAC  NUMBER(8)                    DEFAULT 0                     NOT NULL,
  COD_MENSAJE      NUMBER(3),
  PRG_RUTA         VARCHAR2(60 BYTE)            DEFAULT '.'                   NOT NULL,
  TIP_OOSS         NUMBER(1)                    DEFAULT 0                     NOT NULL,
  IND_ORSERV       VARCHAR2(3 BYTE)             DEFAULT '2',
  COMP_NAME        VARCHAR2(100 BYTE)           DEFAULT 'NO CONFIG',
  CONEX_NAME       VARCHAR2(30 BYTE)            DEFAULT 'NO CONFIG'
);


CREATE UNIQUE INDEX PK_CI_TIPORSERV ON CI_TIPORSERV
(COD_OS);


ALTER TABLE CI_TIPORSERV ADD (
  CONSTRAINT PK_CI_TIPORSERV
  PRIMARY KEY
  (COD_OS)
  USING INDEX PK_CI_TIPORSERV);


------------------------------------------------

CREATE TABLE CI_ORSERV
(
  NUM_OS          NUMBER(10)                    NOT NULL,
  COD_OS          VARCHAR2(5 BYTE)              NOT NULL,
  PRODUCTO        NUMBER(1)                     NOT NULL,
  TIP_INTER       NUMBER(2)                     NOT NULL,
  COD_INTER       NUMBER(10)                    NOT NULL,
  USUARIO         VARCHAR2(30 BYTE),
  FECHA           DATE                          NOT NULL,
  COMENTARIO      VARCHAR2(500 BYTE)            NOT NULL,
  NUM_CARGO       NUMBER(9),
  COD_MODULO      VARCHAR2(2 BYTE),
  ID_GESTOR       NUMBER(10),
  NUM_MOVIMIENTO  NUMBER(9),
  COD_ESTADO      NUMBER(1)
);

COMMENT ON COLUMN CI_ORSERV.NUM_MOVIMIENTO IS 'Numero de movimiento.';

COMMENT ON COLUMN CI_ORSERV.COD_ESTADO IS 'Codigo estado movimiento.';


CREATE INDEX AK_CI_ORSERV ON CI_ORSERV
(COD_OS);


CREATE INDEX AK_CI_ORSERV_INTER ON CI_ORSERV
(TIP_INTER, COD_INTER);


CREATE UNIQUE INDEX PK_CI_ORSERV ON CI_ORSERV
(NUM_OS);


CREATE UNIQUE INDEX PV_ORSERV_NUM_MOV_IE ON CI_ORSERV
(NUM_MOVIMIENTO)
;


ALTER TABLE CI_ORSERV ADD (
  CONSTRAINT PK_CI_ORSERV
  PRIMARY KEY
  (NUM_OS)
  USING INDEX PK_CI_ORSERV);

ALTER TABLE CI_ORSERV ADD (
  CONSTRAINT FK_CI_ORSERV_CI_TIPORSERV 
  FOREIGN KEY (COD_OS) 
  REFERENCES CI_TIPORSERV (COD_OS)  DISABLE);

--------------------------------------------------


