--1.TA_PLANTARIF
-- Descripción: Información de los planes tarifarios.

CREATE TABLE TA_PLANTARIF (
  COD_PRODUCTO       INTEGER                   NOT NULL,
  COD_PLANTARIF      VARCHAR(3)                NOT NULL,
  DES_PLANTARIF      VARCHAR(30)               NOT NULL,
  TIP_TERMINAL       VARCHAR(1),
  COD_LIMCONSUMO     VARCHAR(3)                NOT NULL,
  COD_CARGOBASICO    VARCHAR(3)                NOT NULL,
  TIP_PLANCONSUMO    INTEGER                   NOT NULL,
  TIP_PLANTARIF      VARCHAR(1)                NOT NULL,
  NUM_MINUTOSFF      INTEGER,
  IMP_MINUTOFF       NUMERIC(12,4),
  TIP_UNIDADES       VARCHAR(1)                NOT NULL,
  NUM_UNIDADES       INTEGER                   NOT NULL,
  IND_ARRASTRE       INTEGER                   NOT NULL,
  NUM_DIAS           INTEGER                   NOT NULL,
  NUM_ABONADOS       INTEGER,
  FEC_DESDE          DATE                      NOT NULL,
  FEC_HASTA          DATE,
  IND_FAMILIAR       INTEGER                   DEFAULT 0                      NOT NULL,
  NOM_USUARIO        VARCHAR(40)               DEFAULT 'TARIFICA'             NOT NULL,
  FEC_ULTIMAMOD      DATE                      DEFAULT '1999-01-01'           NOT NULL,
  TIP_UNITAS         CHAR(1)                   DEFAULT 'M'                    NOT NULL,
  IND_TARIFADIFER    INTEGER                   DEFAULT 0                      NOT NULL,
  CLA_PLANTARIF      VARCHAR(3),
  IND_PROPORCS       INTEGER                   DEFAULT 0,
  IND_CARGO_HABIL    INTEGER                   DEFAULT 0,
  NUM_DIAS_EXPIRA    INTEGER                   DEFAULT 0,
  COD_PLAN_COMVERSE  VARCHAR(2),
  IND_FRANCONS       VARCHAR(2)                DEFAULT 'M'                    NOT NULL,
  COD_SERVICIO       INTEGER                                                  ,
  COD_TIPLAN         VARCHAR(5),
  IND_COBRA_SEND     INTEGER                   DEFAULT 1                      NOT NULL,
  IND_BOLSADCTO      VARCHAR(5)                DEFAULT 'C'                    NOT NULL,
  FLG_RANGO          INTEGER                   DEFAULT 0,
  IND_COMER_WEB      INTEGER                   DEFAULT 0                      NOT NULL,
  COD_PROD_PADRE     INTEGER,
  NUM_MESES_RENOVA   INTEGER                   DEFAULT 0                      NOT NULL,
  TIP_RED            VARCHAR(1)                DEFAULT 'M'                    NOT NULL,
  IND_COMPARTIDO     INTEGER                   DEFAULT 0,
  TIP_COBRO          VARCHAR(1)                DEFAULT 'V',
  GRP_PRESTACION     VARCHAR(5)                DEFAULT 'TM'                   NOT NULL,
  COD_GRUPO          VARCHAR(5)                DEFAULT '0'                    NOT NULL,
  COD_PRESTACION     VARCHAR(5)                DEFAULT '01',
  DUR_MINIMA         INTEGER                   DEFAULT 0,
  GRP_PLAN           VARCHAR(5)
);

-- Índices:

CREATE INDEX AK_TA_PLANTARIF_CODLIMCONS ON TA_PLANTARIF (COD_PRODUCTO, COD_LIMCONSUMO);
CREATE INDEX AK_TA_PLANTARIF_TIPPLANTARIF ON TA_PLANTARIF (TIP_PLANTARIF);
CREATE INDEX GE_TAPT_GRPCOD_PRESTACION_IE ON TA_PLANTARIF (FEC_DESDE, FEC_HASTA, GRP_PRESTACION, COD_PRESTACION);
CREATE INDEX GE_TAPT_GRP_PRESTACION_IE ON TA_PLANTARIF (FEC_DESDE, FEC_HASTA, GRP_PRESTACION);
CREATE INDEX X01TA_PLANTARIF ON TA_PLANTARIF (COD_PLANTARIF);

-- Llave primaria:

ALTER TABLE TA_PLANTARIF ADD CONSTRAINT PK_TA_PLANTARIF PRIMARY KEY (COD_PRODUCTO, COD_PLANTARIF);

--2.GE_CATEGORIAS
-- Descripción: Categorías generales.

CREATE TABLE GE_CATEGORIAS (
  COD_CATEGORIA        INTEGER                   NOT NULL,
  DES_CATEGORIA        VARCHAR(50)               NOT NULL,
  IND_ASESOR           CHAR(1)                   DEFAULT 'S',
  IND_VIGENCIA         CHAR(1)                   DEFAULT 'S',
  FEC_IND_VIGENCIA     DATE                      DEFAULT CURRENT_DATE,
  NOM_USU_INDVIGENCIA  VARCHAR(30)               DEFAULT CURRENT_USER,
  FEC_ULTMOD           DATE                      DEFAULT CURRENT_DATE,
  NOM_USUARIO          VARCHAR(30)               DEFAULT CURRENT_USER
);

-- Llave primaria:

ALTER TABLE GE_CATEGORIAS ADD CONSTRAINT PK_GE_CATEGORIAS PRIMARY KEY (COD_CATEGORIA);

--3.GE_CLASCTA
-- Descripción: Clasificación de cuentas.

CREATE TABLE GE_CLASCTA (
  COD_CLASCTA  VARCHAR(2)                  NOT NULL,
  DES_CLASCTA  VARCHAR(30)                 NOT NULL
);

-- Llave primaria:

ALTER TABLE GE_CLASCTA ADD CONSTRAINT PK_GE_CLASCTA PRIMARY KEY (COD_CLASCTA);

--4.GE_TIPIDENT
-- Descripción: Tipos de identificación.

CREATE TABLE GE_TIPIDENT (
  COD_TIPIDENT      VARCHAR(2)                  NOT NULL,
  DES_TIPIDENT      VARCHAR(20)                 NOT NULL,
  IND_PERTRIB       VARCHAR(1)                  NOT NULL,
  IND_SALEFACT      INTEGER                     NOT NULL,
  ORDEN_DISPLAY     INTEGER,
  IND_TIPIDENT      INTEGER,
  COD_TIPIDENTDIAN  VARCHAR(2)
);

-- Llave primaria:

ALTER TABLE GE_TIPIDENT ADD CONSTRAINT PK_GE_TIPIDENT PRIMARY KEY (COD_TIPIDENT);

--5.GE_TIPTARJETAS
-- Descripción: Información de los tipos de tarjetas.

CREATE TABLE GE_TIPTARJETAS (
  COD_TIPTARJETA    VARCHAR(3)                  NOT NULL,
  DES_TIPTARJETA    VARCHAR(40)                 NOT NULL,
  IND_VALBIN        INTEGER                     DEFAULT 0                      NOT NULL,
  COD_TARJETA_ASOC  VARCHAR(3)
);

-- Llave primaria:

ALTER TABLE GE_TIPTARJETAS ADD CONSTRAINT PK_GE_TIPTARJETAS PRIMARY KEY (COD_TIPTARJETA);

--6.GE_SUCURSALES
-- Descripción: Sucursales bancarias.
-- Creación de la tabla GE_SUCURSALES en PostgreSQL:

CREATE TABLE GE_SUCURSALES (
  COD_BANCO      VARCHAR(15)                   NOT NULL,
  COD_SUCURSAL   VARCHAR(4)                    NOT NULL,
  DES_SUCURSAL   VARCHAR(50)                   NOT NULL,
  COD_DIRECCION  BIGINT                        NOT NULL
);

-- Índices:

CREATE INDEX AK_GE_SUCURSALES_GE_DIRECCION ON GE_SUCURSALES (COD_DIRECCION);

-- Llave primaria:

ALTER TABLE GE_SUCURSALES ADD CONSTRAINT PK_GE_SUCURSALES PRIMARY KEY (COD_BANCO, COD_SUCURSAL);

--7.GE_SISPAGO
-- Descripción: Sistemas de pago.

CREATE TABLE GE_SISPAGO (
  COD_SISPAGO  INTEGER                     NOT NULL,
  DES_SISPAGO  VARCHAR(40)                 NOT NULL,
  IND_INTERNO  INTEGER                     NOT NULL,
  IND_MANUAL   INTEGER                     NOT NULL
);

-- Llave primaria:

ALTER TABLE GE_SISPAGO ADD CONSTRAINT PK_GE_SISPAGO PRIMARY KEY (COD_SISPAGO);

--8.GE_PAISES
-- Descripción: Información de los países.

CREATE TABLE GE_PAISES (
  COD_PAIS  VARCHAR(3)                 NOT NULL,
  DES_PAIS  VARCHAR(30)                NOT NULL
);

-- Llave primaria:

ALTER TABLE GE_PAISES ADD CONSTRAINT PK_GE_PAISES PRIMARY KEY (COD_PAIS);

--9.GE_REGIONES
-- Descripción: Regiones de los países.

CREATE TABLE GE_REGIONES (
  COD_REGION  VARCHAR(3)                 NOT NULL,
  DES_REGION  VARCHAR(30)                NOT NULL
);

-- Llave primaria en PostgreSQL:

ALTER TABLE GE_REGIONES ADD CONSTRAINT PK_GE_REGIONES PRIMARY KEY (COD_REGION);

--10.GE_PROVINCIAS
-- Descripción: Provincias en las regiones.

CREATE TABLE GE_PROVINCIAS (
  COD_PROVINCIA  VARCHAR(5)                NOT NULL,
  COD_REGION     VARCHAR(3)                NOT NULL,
  DES_PROVINCIA  VARCHAR(30)               NOT NULL,
  TIP_ZONA       VARCHAR(1)                DEFAULT 'M'                   NOT NULL
);

-- Llave primaria:

ALTER TABLE GE_PROVINCIAS ADD CONSTRAINT PK_GE_PROVINCIAS PRIMARY KEY (COD_PROVINCIA, COD_REGION);

--11.GE_COMUNAS
-- Descripción: Comunas en las provincias.

CREATE TABLE GE_COMUNAS (
  COD_REGION     VARCHAR(3)                NOT NULL,
  COD_PROVINCIA  VARCHAR(5)                NOT NULL,
  COD_COMUNA     VARCHAR(5)                NOT NULL,
  DES_COMUNA     VARCHAR(30)               NOT NULL
);

-- Llave primaria:

ALTER TABLE GE_COMUNAS ADD CONSTRAINT PK_GE_COMUNAS 
  PRIMARY KEY (COD_REGION, COD_PROVINCIA, COD_COMUNA);

--12.GE_OFICINAS
-- Descripción: Oficinas en las comunas.

CREATE TABLE GE_OFICINAS (
  COD_OFICINA          VARCHAR(2)               NOT NULL,
  DES_OFICINA          VARCHAR(40)              NOT NULL,
  NOM_CONTACTO         VARCHAR(40)              NOT NULL,
  COD_REGION           VARCHAR(3),
  COD_PROVINCIA        VARCHAR(5),
  COD_COMUNA           VARCHAR(5),
  COD_DIRECCION        BIGINT                   NOT NULL,
  NUM_TELEF1           VARCHAR(15),
  NUM_TELEF2           VARCHAR(15),
  NUM_FAX              VARCHAR(15),
  OBS_OFICINA          VARCHAR(255),
  IND_REG_NECESIDADES  INTEGER                  DEFAULT 0                     NOT NULL,
  IND_FICHA_RETENCION  INTEGER                  DEFAULT 0                     NOT NULL,
  COD_SUC_PROSEGUR     VARCHAR(3),
  COD_PREFIJO          VARCHAR(3)               DEFAULT '000'                 NOT NULL,
  IND_OFICINA          INTEGER                  DEFAULT 0                     NOT NULL,
  COD_PREFIJO_MATRIZ   VARCHAR(3)               DEFAULT '000'                 NOT NULL,
  CHECK (IND_OFICINA IN (0,1))
);

-- Índices:

CREATE INDEX AK_GE_OFICINAS_COMUNA ON GE_OFICINAS (COD_REGION, COD_PROVINCIA, COD_COMUNA);
CREATE INDEX AK_GE_OFICINAS_DIRECCION ON GE_OFICINAS (COD_DIRECCION, COD_OFICINA);

-- Llave primaria:

ALTER TABLE GE_OFICINAS ADD CONSTRAINT PK_GE_OFICINAS PRIMARY KEY (COD_OFICINA);

--13.GE_CALCLIENTE
-- Descripción: Calificación del cliente.

CREATE TABLE GE_CALCLIENTE (
  COD_CALCLIEN  VARCHAR(2)                 NOT NULL,
  DES_CALCLIEN  VARCHAR(40)                NOT NULL
);

-- Llave primaria:

ALTER TABLE GE_CALCLIENTE ADD CONSTRAINT PK_GE_CALCLIENTE PRIMARY KEY (COD_CALCLIEN);

--14.GE_BANCOS
-- Descripción: Información de los bancos.

CREATE TABLE GE_BANCOS (
  COD_BANCO      VARCHAR(15)                NOT NULL,
  DES_BANCO      VARCHAR(40)                NOT NULL,
  COD_BCOI       INTEGER,
  IND_PAC        INTEGER                    DEFAULT 0                     NOT NULL,
  COD_DICOM      VARCHAR(3),
  COD_BANCO_ON2  VARCHAR(15)                DEFAULT '1'                   NOT NULL
);

-- Llave primaria:

ALTER TABLE GE_BANCOS ADD CONSTRAINT PK_GE_BANCOS PRIMARY KEY (COD_BANCO);

--15.GE_ACTIVIDADES
-- Descripción: Actividades comerciales.

CREATE TABLE GE_ACTIVIDADES (
  COD_ACTIVIDAD  INTEGER                     NOT NULL,
  DES_ACTIVIDAD  VARCHAR(40)                 NOT NULL
);

-- Llave primaria:

ALTER TABLE GE_ACTIVIDADES ADD CONSTRAINT PK_GE_ACTIVIDADES PRIMARY KEY (COD_ACTIVIDAD);

--16.GA_CUENTAS
-- Descripción: Cuentas de los clientes.

CREATE TABLE GA_CUENTAS (
  COD_CUENTA          BIGINT                   NOT NULL,
  DES_CUENTA          VARCHAR(50)              NOT NULL,
  TIP_CUENTA          VARCHAR(1)               NOT NULL,
  NOM_RESPONSABLE     VARCHAR(50)              NOT NULL,
  COD_TIPIDENT        VARCHAR(2)               NOT NULL,
  NUM_IDENT           VARCHAR(20)              NOT NULL,
  COD_DIRECCION       BIGINT                   NOT NULL,
  FEC_ALTA            DATE                     NOT NULL,
  IND_ESTADO          VARCHAR(1)               NOT NULL,
  TEL_CONTACTO        VARCHAR(15),
  IND_SECTOR          VARCHAR(1),
  COD_CLASCTA         VARCHAR(2),
  COD_CATRIBUT        CHAR(1),
  COD_CATEGORIA       INTEGER,
  COD_SECTOR          INTEGER,
  COD_SUBCATEGORIA    VARCHAR(5),
  IND_MULTUSO         CHAR(1)                  DEFAULT 'N'                   NOT NULL,
  IND_CLIEPOTENCIAL   CHAR(1)                  DEFAULT 'N'                   NOT NULL,
  DES_RAZON_SOCIAL    VARCHAR(50),
  FEC_INIVTA_PAC      DATE,
  COD_TIPCOMIS        VARCHAR(2),
  NOM_USUARIO_ASESOR  VARCHAR(30),
  FEC_NACIMIENTO      DATE
);

-- Comentarios:

COMMENT ON TABLE GA_CUENTAS IS 'Cuentas de Clientes';
COMMENT ON COLUMN GA_CUENTAS.COD_CUENTA IS 'Codigo de Cuenta';
COMMENT ON COLUMN GA_CUENTAS.DES_CUENTA IS 'Descripcion de Cuenta';
COMMENT ON COLUMN GA_CUENTAS.TIP_CUENTA IS 'Tipo de Cuenta (P)articular/(E)mpresa';
COMMENT ON COLUMN GA_CUENTAS.NOM_RESPONSABLE IS 'Nombre del Responsable';
COMMENT ON COLUMN GA_CUENTAS.COD_TIPIDENT IS 'Tipo de Identificacion';
COMMENT ON COLUMN GA_CUENTAS.NUM_IDENT IS 'Numero de Identificacion';
COMMENT ON COLUMN GA_CUENTAS.COD_DIRECCION IS 'Codigo de Direccion';
COMMENT ON COLUMN GA_CUENTAS.FEC_ALTA IS 'Fecha de Alta';
COMMENT ON COLUMN GA_CUENTAS.IND_ESTADO IS 'Indicativo de Estado (C)umplimentada/(S)in Cumplimentar';
COMMENT ON COLUMN GA_CUENTAS.TEL_CONTACTO IS 'Telefono de Contacto';
COMMENT ON COLUMN GA_CUENTAS.IND_SECTOR IS 'Indicativo de Sector (P)ublico/P(R)ivado';
COMMENT ON COLUMN GA_CUENTAS.COD_CLASCTA IS 'Codigo de Clasificacion de Cuenta';
COMMENT ON COLUMN GA_CUENTAS.COD_CATRIBUT IS 'Tipo de categoria tributaria de la cuenta';
COMMENT ON COLUMN GA_CUENTAS.COD_CATEGORIA IS 'Tipo de categoria de la cuenta';
COMMENT ON COLUMN GA_CUENTAS.COD_SECTOR IS 'Indicativo de Sector de la categoria';
COMMENT ON COLUMN GA_CUENTAS.COD_SUBCATEGORIA IS 'Subcategoria de la cuenta.';
COMMENT ON COLUMN GA_CUENTAS.IND_MULTUSO IS 'Indicador de Multiples usos.';
COMMENT ON COLUMN GA_CUENTAS.IND_CLIEPOTENCIAL IS 'Indicador de Cuenta Potencial.';
COMMENT ON COLUMN GA_CUENTAS.DES_RAZON_SOCIAL IS 'Razon social de la cuenta potencial.';
COMMENT ON COLUMN GA_CUENTAS.FEC_INIVTA_PAC IS 'Fecha de la primera venta PA en Cuotas del grupo .';
COMMENT ON COLUMN GA_CUENTAS.COD_TIPCOMIS IS 'codigo de comisionista de la primera venta.';
COMMENT ON COLUMN GA_CUENTAS.NOM_USUARIO_ASESOR IS 'NOMBRE USUARIO ASESOR DE LA CUENTA';
COMMENT ON COLUMN GA_CUENTAS.FEC_NACIMIENTO IS 'Fecha de nacimiento Persona Fisica o Moral';

-- Índices:

CREATE INDEX AK_CUENTA_ASESOR ON GA_CUENTAS (NOM_USUARIO_ASESOR);
CREATE INDEX AK_GA_CUENTAS_CATEGORIA ON GA_CUENTAS (COD_CATEGORIA);
CREATE INDEX AK_GA_CUENTAS_NUMIDENT ON GA_CUENTAS (NUM_IDENT);
CREATE INDEX AK_GA_CUENTAS_SUBCATEGORIA ON GA_CUENTAS (COD_SUBCATEGORIA);
CREATE INDEX AK_GA_CUENTA_CLASCTA ON GA_CUENTAS (COD_CLASCTA);
CREATE INDEX AK_GA_CUENTA_DIRECCION ON GA_CUENTAS (COD_DIRECCION);
CREATE INDEX AK_GA_CUENTA_RESPONSABLE ON GA_CUENTAS (NOM_RESPONSABLE);
CREATE INDEX GA_CUENTA_DESCUENTA_IE ON GA_CUENTAS (DES_CUENTA);
CREATE INDEX GA_CUENTA_TELCONTACTO_IE ON GA_CUENTAS (TEL_CONTACTO);

-- Llave primaria:

ALTER TABLE GA_CUENTAS ADD CONSTRAINT PK_GA_CUENTAS PRIMARY KEY (COD_CUENTA);

--17.GE_ALMS
-- Descripción: Información sobre almacenes.

CREATE TABLE GE_ALMS (
  COD_ALM            VARCHAR(3)                NOT NULL,
  DES_ALM            VARCHAR(30)               NOT NULL,
  COD_OPERADORA_SCL  VARCHAR(5),
  COD_TIPO_ALM       VARCHAR(5)
);

-- Llave primaria:

ALTER TABLE GE_ALMS ADD CONSTRAINT PK_GE_ALMS PRIMARY KEY (COD_ALM);

--18.GE_PRODUCTOS
-- Descripción: Información de productos.

CREATE TABLE GE_PRODUCTOS (
  COD_PRODUCTO  INTEGER                    NOT NULL,
  IND_REAL      INTEGER                    NOT NULL,
  DES_PRODUCTO  VARCHAR(20)                NOT NULL
);

-- Llave primaria:

ALTER TABLE GE_PRODUCTOS ADD CONSTRAINT PK_GE_PRODUCTOS PRIMARY KEY (COD_PRODUCTO);

--20.ICG_CENTRAL
-- Descripción: Información de las centrales del sistema.

CREATE TABLE ICG_CENTRAL (
  COD_CENTRAL      INTEGER                    NOT NULL,
  COD_PRODUCTO     INTEGER                    NOT NULL,
  NOM_CENTRAL      VARCHAR(15)                NOT NULL,
  COD_NEMOTEC      VARCHAR(15)                NOT NULL,
  COD_ALM          VARCHAR(3)                 NOT NULL,
  NUM_MAXINTENTOS  INTEGER                    NOT NULL,
  COD_SISTEMA      INTEGER                    NOT NULL,
  COD_COBERTURA    INTEGER                    DEFAULT 1                     NOT NULL,
  TIE_RESPUESTA    NUMERIC(12,4),
  NODOCOM          VARCHAR(20),
  COD_TECNOLOGIA   VARCHAR(7)                 NOT NULL,
  COD_HLR          VARCHAR(10)
);

-- Índices:

CREATE INDEX FK_I_ICGEN_GEALMS ON ICG_CENTRAL (COD_ALM);
CREATE INDEX FK_I_ICGEN_ICCEN ON ICG_CENTRAL (COD_CENTRAL);
CREATE INDEX FK_I_ICGEN_ICGSIS ON ICG_CENTRAL (COD_SISTEMA);

-- Llave primaria:

ALTER TABLE ICG_CENTRAL ADD CONSTRAINT PK_ICG_CENTRAL PRIMARY KEY (COD_PRODUCTO, COD_CENTRAL);

--22.GE_CLIENTES
-- Descripción: Información de los clientes.

CREATE TABLE GE_CLIENTES (
  COD_CLIENTE             BIGINT                NOT NULL,
  NOM_CLIENTE             VARCHAR(50)           NOT NULL,
  COD_TIPIDENT            VARCHAR(2)            NOT NULL,
  NUM_IDENT               VARCHAR(20)           NOT NULL,
  COD_CALCLIEN            VARCHAR(2)            NOT NULL,
  IND_SITUACION           VARCHAR(2)            NOT NULL,
  FEC_ALTA                DATE                  NOT NULL,
  IND_FACTUR              INTEGER               NOT NULL,
  IND_TRASPASO            VARCHAR(1)            NOT NULL,
  IND_AGENTE              VARCHAR(1)            NOT NULL,
  FEC_ULTMOD              DATE                  NOT NULL,
  NUM_FAX                 VARCHAR(15),
  IND_MANDATO             INTEGER,
  NOM_USUARORA            VARCHAR(30)           NOT NULL,
  IND_ALTA                VARCHAR(1)            NOT NULL,
  COD_CUENTA              BIGINT                NOT NULL,
  IND_ACEPVENT            VARCHAR(1)            NOT NULL,
  COD_ABC                 VARCHAR(1)            NOT NULL,
  COD_123                 INTEGER               NOT NULL,
  COD_ACTIVIDAD           INTEGER,
  COD_PAIS                VARCHAR(3),
  TEF_CLIENTE1            VARCHAR(15),
  NUM_ABOCEL              INTEGER,
  TEF_CLIENTE2            VARCHAR(15),
  NUM_ABOBEEP             INTEGER,
  IND_DEBITO              VARCHAR(1),
  NUM_ABOTRUNK            INTEGER,
  COD_PROSPECTO           BIGINT,
  NUM_ABOTREK             INTEGER,
  COD_SISPAGO             INTEGER,
  NOM_APECLIEN1           VARCHAR(20),
  NOM_EMAIL               VARCHAR(255),
  NUM_ABORENT             INTEGER,
  NOM_APECLIEN2           VARCHAR(20),
  NUM_ABOROAMING          INTEGER,
  FEC_ACEPVENT            DATE,
  IMP_STOPDEBIT           NUMERIC(12,4),
  COD_BANCO               VARCHAR(15),
  COD_SUCURSAL            VARCHAR(4),
  IND_TIPCUENTA           VARCHAR(1),
  COD_TIPTARJETA          VARCHAR(3),
  NUM_CTACORR             VARCHAR(18),
  NUM_TARJETA             VARCHAR(18),
  FEC_VENCITARJ           DATE,
  COD_BANCOTARJ           VARCHAR(15),
  COD_TIPIDTRIB           VARCHAR(2),
  NUM_IDENTTRIB           VARCHAR(20),
  COD_TIPIDENTAPOR        VARCHAR(2),
  NUM_IDENTAPOR           VARCHAR(20),
  NOM_APODERADO           VARCHAR(40),
  COD_OFICINA             VARCHAR(2),
  FEC_BAJA                DATE,
  COD_COBRADOR            INTEGER,
  COD_PINCLI              VARCHAR(4),
  COD_CICLO               INTEGER,
  NUM_CELULAR             BIGINT,
  IND_TIPPERSONA          VARCHAR(1)            DEFAULT 'F',
  COD_CICLONUE            INTEGER,
  COD_CATEGORIA           INTEGER,
  COD_SECTOR              INTEGER,
  COD_SUPERVISOR          INTEGER,
  IND_ESTCIVIL            CHAR(1),
  FEC_NACIMIEN            DATE,
  IND_SEXO                CHAR(1),
  NUM_INT_GRUP_FAM        INTEGER,
  COD_NPI                 INTEGER,
  COD_SUBCATEGORIA        VARCHAR(5),
  COD_USO                 VARCHAR(5),
  COD_IDIOMA              VARCHAR(5)            DEFAULT '1'                   NOT NULL,
  COD_TIPIDENT2           VARCHAR(2),
  NUM_IDENT2              VARCHAR(20),
  NOM_USUARIO_ASESOR      VARCHAR(30),
  COD_OPERADORA           VARCHAR(5)            DEFAULT 'TMG'                 NOT NULL,
  IND_FACTURAELECTRONICA  INTEGER               DEFAULT 0                     NOT NULL,
  NOM_CONYUGE             VARCHAR(50),
  COD_OPERADOR            INTEGER,
  MENS_PROMO              VARCHAR(1)            DEFAULT 'A',
  COD_PROFESION           INTEGER,
  NOM_EMPRESA             VARCHAR(50),
  TEF_OFICINA             VARCHAR(15),
  COD_OCUPACION           INTEGER,
  IMP_INGRESOS            NUMERIC(14,4),
  NOM_JEFE                VARCHAR(50),
  CANT_ANLABOR            VARCHAR(2),
  NOM_REFER1              VARCHAR(50),
  TEF_REFER1              VARCHAR(15),
  NOM_REFER2              VARCHAR(50),
  COD_TIPO                VARCHAR(5)            DEFAULT '3',
  COD_COLOR               VARCHAR(5)            DEFAULT '10',
  COD_CREDITICIA          VARCHAR(5)            DEFAULT 'EXC',
  COD_SEGMENTO            VARCHAR(5)            DEFAULT '1',
  COD_CALIFICACION        VARCHAR(5)            DEFAULT 'A',
  NOM_TITULARTARJETA      VARCHAR(50),
  OBS_PAC                 VARCHAR(100),
  TEF_REFER2              VARCHAR(15)
);

-- Comentarios en PostgreSQL:
COMMENT ON TABLE GE_CLIENTES IS 'Clientes del sistema.';
COMMENT ON COLUMN GE_CLIENTES.COD_CLIENTE IS 'Codigo Cliente';
COMMENT ON COLUMN GE_CLIENTES.NOM_CLIENTE IS 'Nombre Cliente';
COMMENT ON COLUMN GE_CLIENTES.COD_TIPIDENT IS 'Tipo Identificacion Cliente';
COMMENT ON COLUMN GE_CLIENTES.NUM_IDENT IS 'Numero Identificacion Cliente';
COMMENT ON COLUMN GE_CLIENTES.COD_CALCLIEN IS 'Codigo Calidad Cliente';
COMMENT ON COLUMN GE_CLIENTES.IND_SITUACION IS 'Situacion Cliente; (S)in Cumplimentar, (C)umplimentado';
COMMENT ON COLUMN GE_CLIENTES.FEC_ALTA IS 'Fecha de Alta';
COMMENT ON COLUMN GE_CLIENTES.IND_FACTUR IS 'Indicativo de Facturable ; Si(1), No(0)';
COMMENT ON COLUMN GE_CLIENTES.IND_TRASPASO IS 'Indicativo de Traspasos ; Si(S), No(N)';
COMMENT ON COLUMN GE_CLIENTES.IND_AGENTE IS 'Indicativo de Agente ; Si(S), No(N)';
COMMENT ON COLUMN GE_CLIENTES.FEC_ULTMOD IS 'Fecha Ultima Modificacion Cliente';
COMMENT ON COLUMN GE_CLIENTES.NUM_FAX IS 'Numero de Fax del Cliente';
COMMENT ON COLUMN GE_CLIENTES.IND_MANDATO IS 'Indicativo Mandato Domiciliacion ; Si (0), No (1)';
COMMENT ON COLUMN GE_CLIENTES.NOM_USUARORA IS 'Usuario Creador Cliente';
COMMENT ON COLUMN GE_CLIENTES.IND_ALTA IS 'Indicador Procedencia de Alta ; Venta (V) Traspaso (T) Agente (A) Roaming (R) Rent a Phone (P)';
COMMENT ON COLUMN GE_CLIENTES.COD_CUENTA IS 'Codigo Cuenta Cliente';
COMMENT ON COLUMN GE_CLIENTES.IND_ACEPVENT IS 'Indicativo Aceptacion Venta ; Si(1), No(0)';
COMMENT ON COLUMN GE_CLIENTES.COD_ABC IS 'Codigo Clasificacion ABC';
COMMENT ON COLUMN GE_CLIENTES.COD_123 IS 'Codigo Clasificacion 123';
COMMENT ON COLUMN GE_CLIENTES.COD_ACTIVIDAD IS 'Codigo Actividad';
COMMENT ON COLUMN GE_CLIENTES.COD_PAIS IS 'Codigo del pais';
COMMENT ON COLUMN GE_CLIENTES.TEF_CLIENTE1 IS 'Telefono Contacto Cliente';
COMMENT ON COLUMN GE_CLIENTES.NUM_ABOCEL IS 'Numero Abonados Celular';
COMMENT ON COLUMN GE_CLIENTES.TEF_CLIENTE2 IS 'Telefono Contacto Cliente';
COMMENT ON COLUMN GE_CLIENTES.NUM_ABOBEEP IS 'Numero Abonados Beeper';
COMMENT ON COLUMN GE_CLIENTES.IND_DEBITO IS 'Indicativo Debito ; Automatico (A), Manual (M)';
COMMENT ON COLUMN GE_CLIENTES.NUM_ABOTRUNK IS 'Numero Abonados Trunking';
COMMENT ON COLUMN GE_CLIENTES.COD_PROSPECTO IS 'Codigo de Prospecto Origen';
COMMENT ON COLUMN GE_CLIENTES.NUM_ABOTREK IS 'Numero Abonados Trek';
COMMENT ON COLUMN GE_CLIENTES.COD_SISPAGO IS 'Sistema de pago';
COMMENT ON COLUMN GE_CLIENTES.NOM_APECLIEN1 IS 'Primer Apellido Cliente';
COMMENT ON COLUMN GE_CLIENTES.NOM_EMAIL IS 'Direccion E-Mail del Cliente';
COMMENT ON COLUMN GE_CLIENTES.NUM_ABORENT IS 'Numero Abonados Rent a Phone';
COMMENT ON COLUMN GE_CLIENTES.NOM_APECLIEN2 IS 'Segundo Apellido Cliente';
COMMENT ON COLUMN GE_CLIENTES.NUM_ABOROAMING IS 'Numero Abonados Roaming';
COMMENT ON COLUMN GE_CLIENTES.FEC_ACEPVENT IS 'Fecha de aceptacion de la venta';
COMMENT ON COLUMN GE_CLIENTES.IMP_STOPDEBIT IS 'Importe Limite Debito';
COMMENT ON COLUMN GE_CLIENTES.COD_BANCO IS 'Codigo de Banco';
COMMENT ON COLUMN GE_CLIENTES.COD_SUCURSAL IS 'Codigo de Sucursal';
COMMENT ON COLUMN GE_CLIENTES.IND_TIPCUENTA IS 'Indicativo Tipo Cuenta ; Corriente (C), Ahorro (A)';
COMMENT ON COLUMN GE_CLIENTES.COD_TIPTARJETA IS 'Codigo Tipo Tarjeta';
COMMENT ON COLUMN GE_CLIENTES.NUM_CTACORR IS 'Numero cuenta corriente';
COMMENT ON COLUMN GE_CLIENTES.NUM_TARJETA IS 'Numero de tarjeta';
COMMENT ON COLUMN GE_CLIENTES.FEC_VENCITARJ IS 'Fecha vencimiento de la tarjeta';
COMMENT ON COLUMN GE_CLIENTES.COD_BANCOTARJ IS 'Codigo banco tarjeta';
COMMENT ON COLUMN GE_CLIENTES.COD_TIPIDTRIB IS 'Codigo Tipo Identificacion Tributaria';
COMMENT ON COLUMN GE_CLIENTES.NUM_IDENTTRIB IS 'Numero Identificacion Tributaria';
COMMENT ON COLUMN GE_CLIENTES.COD_TIPIDENTAPOR IS 'Codigo Tipo Identificacion Apoderado';
COMMENT ON COLUMN GE_CLIENTES.NUM_IDENTAPOR IS 'Numero identificador del apoderado';
COMMENT ON COLUMN GE_CLIENTES.NOM_APODERADO IS 'Nombre del apoderado';
COMMENT ON COLUMN GE_CLIENTES.COD_OFICINA IS 'Codigo de oficina';
COMMENT ON COLUMN GE_CLIENTES.FEC_BAJA IS 'Fecha de baja';
COMMENT ON COLUMN GE_CLIENTES.COD_COBRADOR IS 'Codigo de cobrador';
COMMENT ON COLUMN GE_CLIENTES.COD_PINCLI IS 'Codigo de identificacion del cliente';
COMMENT ON COLUMN GE_CLIENTES.COD_CICLONUE IS 'Indicador, si el cliente tiene pendiente un cambio de ciclo';
COMMENT ON COLUMN GE_CLIENTES.COD_CATEGORIA IS 'Codigo Categoria de Cliente.';
COMMENT ON COLUMN GE_CLIENTES.COD_SECTOR IS 'Codigo Sector Publico o Privado.';
COMMENT ON COLUMN GE_CLIENTES.COD_SUPERVISOR IS 'Codigo Supervisor.';
COMMENT ON COLUMN GE_CLIENTES.IND_ESTCIVIL IS 'Estado civil del usuario: C=Casado | S=Soltero | D=Divorciado | V=Viudo | O=Otro';
COMMENT ON COLUMN GE_CLIENTES.FEC_NACIMIEN IS 'Fecha nacimiento del cliente.';
COMMENT ON COLUMN GE_CLIENTES.IND_SEXO IS 'Sexo del cliente: M=Masculino | F=Femenino.';
COMMENT ON COLUMN GE_CLIENTES.NUM_INT_GRUP_FAM IS 'Numero de integrantes del grupo familiar';
COMMENT ON COLUMN GE_CLIENTES.COD_NPI IS 'Indicador de Privacidad; 0:Sin Privaci
dad, 1: Con Privacidad';
COMMENT ON COLUMN GE_CLIENTES.COD_SUBCATEGORIA IS 'Subcategoria del cliente.';
COMMENT ON COLUMN GE_CLIENTES.COD_USO IS 'Codigo del uso de la cuenta.';
COMMENT ON COLUMN GE_CLIENTES.COD_IDIOMA IS 'Idioma del Cliente.';
COMMENT ON COLUMN GE_CLIENTES.COD_TIPIDENT2 IS 'Codigo de Tipo de Idioma Opcional.';
COMMENT ON COLUMN GE_CLIENTES.NUM_IDENT2 IS 'Numero de Identificacion Opcional.';
COMMENT ON COLUMN GE_CLIENTES.NOM_USUARIO_ASESOR IS 'NOMBRE USUARIO ASESOR DEL CLIENTE';
COMMENT ON COLUMN GE_CLIENTES.COD_OPERADORA IS 'Codigo de Operadora del Cliente.';
COMMENT ON COLUMN GE_CLIENTES.NOM_CONYUGE IS 'Nombre conyuge';
COMMENT ON COLUMN GE_CLIENTES.COD_OPERADOR IS 'Operadora Anterior';
COMMENT ON COLUMN GE_CLIENTES.MENS_PROMO IS 'Desea recibir mensajes promocionales';
COMMENT ON COLUMN GE_CLIENTES.COD_PROFESION IS 'Profesion';
COMMENT ON COLUMN GE_CLIENTES.NOM_EMPRESA IS 'Nombre Empresa';
COMMENT ON COLUMN GE_CLIENTES.TEF_OFICINA IS 'Telefono Oficina';
COMMENT ON COLUMN GE_CLIENTES.COD_OCUPACION IS 'Cargo';
COMMENT ON COLUMN GE_CLIENTES.IMP_INGRESOS IS 'Ingresos Mensuales';
COMMENT ON COLUMN GE_CLIENTES.NOM_JEFE IS 'Jefe Inmediato';
COMMENT ON COLUMN GE_CLIENTES.CANT_ANLABOR IS 'A?os Laborando';
COMMENT ON COLUMN GE_CLIENTES.NOM_REFER1 IS 'Nombre Referencia I';
COMMENT ON COLUMN GE_CLIENTES.TEF_REFER1 IS 'Telefono';
COMMENT ON COLUMN GE_CLIENTES.NOM_REFER2 IS 'Nombre Referencia II';
COMMENT ON COLUMN GE_CLIENTES.COD_TIPO IS 'Tipo cliente';
COMMENT ON COLUMN GE_CLIENTES.COD_COLOR IS 'Color';
COMMENT ON COLUMN GE_CLIENTES.COD_CREDITICIA IS 'Crediticia';
COMMENT ON COLUMN GE_CLIENTES.COD_SEGMENTO IS 'Categoria de Cobros CAMPO YA EXISTE';
COMMENT ON COLUMN GE_CLIENTES.COD_CALIFICACION IS 'Segmento';
COMMENT ON COLUMN GE_CLIENTES.NOM_TITULARTARJETA IS 'Calificacion';
COMMENT ON COLUMN GE_CLIENTES.OBS_PAC IS 'Titular tarjeta';
COMMENT ON COLUMN GE_CLIENTES.TEF_REFER2 IS 'Telefono';


-- Índices:
CREATE INDEX AK_CLIENTE_ASESOR_USO ON GE_CLIENTES (NOM_USUARIO_ASESOR, COD_USO);
CREATE INDEX AK_GECLIENTES_CELULAR ON GE_CLIENTES (NUM_CELULAR);
CREATE INDEX AK_GE_CLIENTES_ACTIVIDADES ON GE_CLIENTES (COD_ACTIVIDAD);
CREATE INDEX AK_GE_CLIENTES_BANCOS ON GE_CLIENTES (COD_BANCOTARJ);
CREATE INDEX AK_GE_CLIENTES_CALCLIENTE ON GE_CLIENTES (COD_CALCLIEN);
CREATE INDEX AK_GE_CLIENTES_CATEGORIA ON GE_CLIENTES (COD_CATEGORIA);
CREATE INDEX AK_GE_CLIENTES_COBRADOR ON GE_CLIENTES (COD_COBRADOR);
CREATE INDEX AK_GE_CLIENTES_OFICINAS ON GE_CLIENTES (COD_OFICINA);
CREATE INDEX AK_GE_CLIENTES_PAISES ON GE_CLIENTES (COD_PAIS);
CREATE INDEX AK_GE_CLIENTES_SISPAGO ON GE_CLIENTES (COD_SISPAGO);
CREATE INDEX AK_GE_CLIENTES_SUBCATEGORIA ON GE_CLIENTES (COD_SUBCATEGORIA);
CREATE INDEX AK_GE_CLIENTES_SUCURSALES ON GE_CLIENTES (COD_BANCO, COD_SUCURSAL);
CREATE INDEX AK_GE_CLIENTES_TIPIDENTAPOR ON GE_CLIENTES (COD_TIPIDENTAPOR);
CREATE INDEX AK_GE_CLIENTES_TIPIDTRIB ON GE_CLIENTES (COD_TIPIDTRIB);
CREATE INDEX AK_GE_CLIENTES_TIPTARJETA ON GE_CLIENTES (COD_TIPTARJETA);
CREATE INDEX AK_GE_CLIENTES_USARORA ON GE_CLIENTES (NOM_USUARORA);
CREATE INDEX AK_GE_CLIENTE_CUENTA ON GE_CLIENTES (COD_CUENTA);
CREATE INDEX AK_GE_CLIENTE_IDENTIFICACION ON GE_CLIENTES (COD_TIPIDENT, NUM_IDENT);
CREATE INDEX AK_GE_CLIENTE_NOMCLI ON GE_CLIENTES (NOM_CLIENTE);

-- Llave primaria:
ALTER TABLE GE_CLIENTES ADD CONSTRAINT PK_GE_CLIENTES PRIMARY KEY (COD_CLIENTE);

--23.GE_CELDAS
-- Descripción: Información de las celdas.

CREATE TABLE GE_CELDAS (
  COD_CELDA    VARCHAR(7)                 NOT NULL,
  COD_SUBALM   VARCHAR(5)                 NOT NULL,
  DES_CELDA    VARCHAR(50)                NOT NULL,
  COD_SUBALM2  VARCHAR(5)
);

-- Índice:

CREATE INDEX AK_CELDAS_SUBALM ON GE_CELDAS (COD_SUBALM);

-- Llave primaria:

ALTER TABLE GE_CELDAS ADD CONSTRAINT PK_GE_CELDAS PRIMARY KEY (COD_CELDA);

--24.GA_TIPCONTRATO
-- Descripción: Tipos de contratos.

CREATE TABLE GA_TIPCONTRATO (
  COD_PRODUCTO     INTEGER                  NOT NULL,
  COD_TIPCONTRATO  VARCHAR(3)               NOT NULL,
  DES_TIPCONTRATO  VARCHAR(30)              NOT NULL,
  FEC_DESDE        DATE                     NOT NULL,
  FEC_HASTA        DATE,
  IND_CONTSEG      VARCHAR(3),
  IND_CONTCEL      VARCHAR(1),
  IND_COMODATO     INTEGER,
  CANAL_VTA        INTEGER,
  MESES_MINIMO     INTEGER,
  IND_PROCEQUI     VARCHAR(1)               DEFAULT 'I'                   NOT NULL,
  IND_PRECIOLISTA  VARCHAR(1)               DEFAULT '1'                   NOT NULL,
  IND_GMC          VARCHAR(3)               DEFAULT '0'                   NOT NULL
);

-- Llave primaria:

ALTER TABLE GA_TIPCONTRATO ADD CONSTRAINT PK_GA_TIPCONTRATO PRIMARY KEY (COD_PRODUCTO, COD_TIPCONTRATO);

--25.GA_PLANSERV
-- Descripción: Planes de servicios.

CREATE TABLE GA_PLANSERV (
  COD_PRODUCTO  INTEGER                    NOT NULL,
  COD_PLANSERV  VARCHAR(3)                 NOT NULL,
  DES_PLANSERV  VARCHAR(30)                NOT NULL,
  FEC_DESDE     DATE                       NOT NULL,
  FEC_HASTA     DATE
);

-- Llave primaria:

ALTER TABLE GA_PLANSERV ADD CONSTRAINT PK_GA_PLANSERV PRIMARY KEY (COD_PRODUCTO, COD_PLANSERV);

--26.FA_CICLOS
-- Descripción: Ciclos de facturación.

CREATE TABLE FA_CICLOS (
  COD_CICLO  INTEGER                    NOT NULL,
  DES_CICLO  VARCHAR(40)                NOT NULL,
  DIG_D      INTEGER                    NOT NULL,
  DIG_C      INTEGER                    NOT NULL,
  DIG_SEC    INTEGER                    DEFAULT 0                     NOT NULL
);

-- Llave primaria:

ALTER TABLE FA_CICLOS ADD CONSTRAINT PK_FA_CICLOS PRIMARY KEY (COD_CICLO);

--27.GA_ABOCEL
-- Descripción: Abonados de la red celular.

CREATE TABLE GA_ABOCEL (
  NUM_ABONADO            BIGINT                 NOT NULL,
  NUM_CELULAR            BIGINT                 NOT NULL,
  COD_PRODUCTO           INTEGER                DEFAULT 1                     NOT NULL,
  COD_CLIENTE            BIGINT                 NOT NULL,
  COD_CUENTA             BIGINT                 NOT NULL,
  COD_SUBCUENTA          VARCHAR(15)            NOT NULL,
  COD_USUARIO            BIGINT                 NOT NULL,
  COD_REGION             VARCHAR(3)             NOT NULL,
  COD_PROVINCIA          VARCHAR(5)             NOT NULL,
  COD_CIUDAD             VARCHAR(5)             NOT NULL,
  COD_CELDA              VARCHAR(7)             NOT NULL,
  COD_CENTRAL            INTEGER                NOT NULL,
  COD_USO                INTEGER                NOT NULL,
  COD_SITUACION          VARCHAR(3)             NOT NULL,
  IND_PROCALTA           VARCHAR(1)             NOT NULL,
  IND_PROCEQUI           VARCHAR(2)             NOT NULL,
  COD_VENDEDOR           INTEGER                NOT NULL,
  COD_VENDEDOR_AGENTE    INTEGER                NOT NULL,
  TIP_PLANTARIF          VARCHAR(1)             NOT NULL,
  TIP_TERMINAL           VARCHAR(1)             NOT NULL,
  COD_PLANTARIF          VARCHAR(3)             NOT NULL,
  COD_CARGOBASICO        VARCHAR(3)             NOT NULL,
  COD_PLANSERV           VARCHAR(3)             NOT NULL,
  COD_LIMCONSUMO         VARCHAR(5),
  NUM_SERIE              VARCHAR(25)            NOT NULL,
  NUM_SERIEHEX           VARCHAR(8)             NOT NULL,
  NOM_USUARORA           VARCHAR(30)            NOT NULL,
  FEC_ALTA               DATE                   NOT NULL,
  NUM_PERCONTRATO        INTEGER                DEFAULT 1                     NOT NULL,
  COD_ESTADO             VARCHAR(10),
  NUM_SERIEMEC           VARCHAR(20),
  COD_HOLDING            BIGINT,
  COD_EMPRESA            BIGINT,
  COD_GRPSERV            VARCHAR(2),
  IND_SUPERTEL           INTEGER,
  NUM_TELEFIJA           VARCHAR(15),
  COD_OPREDFIJA          INTEGER,
  COD_CARRIER            INTEGER,
  IND_PREPAGO            INTEGER,
  IND_PLEXSYS            INTEGER,
  COD_CENTRAL_PLEX       INTEGER,
  NUM_CELULAR_PLEX       BIGINT,
  NUM_VENTA              BIGINT,
  COD_MODVENTA           INTEGER,
  COD_TIPCONTRATO        VARCHAR(3),
  NUM_CONTRATO           VARCHAR(21),
  NUM_ANEXO              VARCHAR(21),
  FEC_CUMPLAN            DATE,
  COD_CREDMOR            INTEGER,
  COD_CREDCON            INTEGER,
  COD_CICLO              INTEGER,
  IND_FACTUR             INTEGER,
  IND_SUSPEN             INTEGER,
  IND_REHABI             INTEGER,
  IND_INSGUIAS           INTEGER,
  FEC_FINCONTRA          DATE,
  FEC_RECDOCUM           DATE,
  FEC_CUMPLIMEN          DATE,
  FEC_ACEPVENTA          DATE,
  FEC_ACTCEN             DATE,
  FEC_BAJA               DATE,
  FEC_BAJACEN            DATE,
  FEC_ULTMOD             DATE,
  COD_CAUSABAJA          VARCHAR(2),
  NUM_PERSONAL           VARCHAR(4),
  IND_SEGURO             INTEGER,
  CLASE_SERVICIO         VARCHAR(255),
  PERFIL_ABONADO         VARCHAR(255),
  NUM_MIN                VARCHAR(3)             DEFAULT '730',
  COD_VENDEALER          INTEGER,
  IND_DISP               INTEGER,
  COD_PASSWORD           VARCHAR(7),
  IND_PASSWORD           CHAR(1),
  COD_AFINIDAD           INTEGER,
  FEC_PRORROGA           DATE,
  IND_EQPRESTADO         VARCHAR(1),
  FLG_CONTDIGI           CHAR(1),
  FEC_ALTANTRAS          DATE,
  COD_INDEMNIZACION      INTEGER,
  NUM_IMEI               VARCHAR(25),
  COD_TECNOLOGIA         VARCHAR(7),
  NUM_MIN_MDN            VARCHAR(10),
  FEC_ACTIVACION         DATE,
  IND_TELEFONO           INTEGER                DEFAULT 6                     NOT NULL,
  COD_OFICINA_PRINCIPAL  VARCHAR(2),
  COD_CAUSA_VENTA        VARCHAR(5),
  COD_OPERACION          VARCHAR(5),
  COD_PRESTACION         VARCHAR(5),
  MTO_VALOR_REFERENCIA   NUMERIC(14,4),
  COD_MONEDA             VARCHAR(3),
  TIPO_PRIMARIACARRIER   VARCHAR(3),
  OBS_INSTANCIA          VARCHAR(50)
);

-- Comentarios:
COMMENT ON TABLE GA_ABOCEL IS 'Abonados Red Celular';
COMMENT ON COLUMN GA_ABOCEL.NUM_ABONADO IS 'Secuencia Numero Abonado';
COMMENT ON COLUMN GA_ABOCEL.NUM_CELULAR IS 'Numero de Celular';
COMMENT ON COLUMN GA_ABOCEL.COD_PRODUCTO IS 'Tipo de Producto';
COMMENT ON COLUMN GA_ABOCEL.COD_CLIENTE IS 'Codigo de Cliente';
COMMENT ON COLUMN GA_ABOCEL.COD_CUENTA IS 'Codigo de Cuenta';
COMMENT ON COLUMN GA_ABOCEL.COD_SUBCUENTA IS 'Codigo de Subcuenta';
COMMENT ON COLUMN GA_ABOCEL.COD_USUARIO IS 'Codigo de Usuario Producto';
COMMENT ON COLUMN GA_ABOCEL.COD_REGION IS 'Codigo de Region';
COMMENT ON COLUMN GA_ABOCEL.COD_PROVINCIA IS 'Codigo de Provincia';
COMMENT ON COLUMN GA_ABOCEL.COD_CIUDAD IS 'Codigo de Ciudad';
COMMENT ON COLUMN GA_ABOCEL.COD_CELDA IS 'Codigo de Celda';
COMMENT ON COLUMN GA_ABOCEL.COD_CENTRAL IS 'Codigo de Central';
COMMENT ON COLUMN GA_ABOCEL.COD_USO IS 'Codigo de Uso de Numeracion';
COMMENT ON COLUMN GA_ABOCEL.COD_SITUACION IS 'Codigo de Situacion de Abonado';
COMMENT ON COLUMN GA_ABOCEL.IND_PROCALTA IS 'Indicativo de Procedencia Alta ; Interna (I), Externa (E)';
COMMENT ON COLUMN GA_ABOCEL.IND_PROCEQUI IS 'Indicativo de Procedencia Equipo ; Interno (I), Externo (E), Subsidiado (S)';
COMMENT ON COLUMN GA_ABOCEL.COD_VENDEDOR IS 'Codigo de Vendedor';
COMMENT ON COLUMN GA_ABOCEL.COD_VENDEDOR_AGENTE IS 'Codigo de Agente';
COMMENT ON COLUMN GA_ABOCEL.TIP_PLANTARIF IS 'Tipo de Plan Tarifario ; Individual (I), Empresa (E), Holding (H)';
COMMENT ON COLUMN GA_ABOCEL.TIP_TERMINAL IS 'Tipo de Terminal ; Analogico (A), Digital (D)';
COMMENT ON COLUMN GA_ABOCEL.COD_PLANTARIF IS 'Codigo de Plan Tarifario';
COMMENT ON COLUMN GA_ABOCEL.COD_CARGOBASICO IS 'Codigo Cargo Basico';
COMMENT ON COLUMN GA_ABOCEL.COD_PLANSERV IS 'Codigo de Plan de Servicios';
COMMENT ON COLUMN GA_ABOCEL.COD_LIMCONSUMO IS 'Codigo de Limite de Consumo';
COMMENT ON COLUMN GA_ABOCEL.NUM_SERIE IS 'Numero de Serie Decimal';
COMMENT ON COLUMN GA_ABOCEL.NUM_SERIEHEX IS 'Numero de Serie Hexadecimal';
COMMENT ON COLUMN GA_ABOCEL.NOM_USUARORA IS 'Usuario Creador Abonado';
COMMENT ON COLUMN GA_ABOCEL.FEC_ALTA IS 'Fecha de Alta Abonado';
COMMENT ON COLUMN GA_ABOCEL.NUM_PERCONTRATO IS 'Numero del Periodo de Contrato';
COMMENT ON COLUMN GA_ABOCEL.COD_ESTADO IS 'Estado en Cartera de Cobros';
COMMENT ON COLUMN GA_ABOCEL.NUM_SERIEMEC IS 'Numero de Serie Mecanico';
COMMENT ON COLUMN GA_ABOCEL.COD_HOLDING IS 'Holding en el cual se encuentra incluido el abonado';
COMMENT ON COLUMN GA_ABOCEL.COD_EMPRESA IS 'Empresa en la cual se encuentra incluido el abonado';
COMMENT ON COLUMN GA_ABOCEL.COD_GRPSERV IS 'Grupo de Cobro de Servicios en el cual se encuentra incluido el abonado';
COMMENT ON COLUMN GA_ABOCEL.IND_SUPERTEL IS 'Indicativo Modalidad Supertelefono ; No (0), Si (1)';
COMMENT ON COLUMN GA_ABOCEL.NUM_TELEFIJA IS 'Numero de telefonia Fija';
COMMENT ON COLUMN GA_ABOCEL.COD_OPREDFIJA IS 'Operador de Red Fija';
COMMENT ON COLUMN GA_ABOCEL.COD_CARRIER IS 'Operador de Carrie';
COMMENT ON COLUMN GA_ABOCEL.IND_PREPAGO IS 'Indicasivo de Prepago No(0), Si(1)';
COMMENT ON COLUMN GA_ABOCEL.IND_PLEXSYS IS 'Indicativo Abonado Zona Plexsys; No (0), Si (1)';
COMMENT ON COLUMN GA_ABOCEL.COD_CENTRAL_PLEX IS 'Codigo Segunda Central Abonados Plexsys';
COMMENT ON COLUMN GA_ABOCEL.NUM_CELULAR_PLEX IS 'Segundo Numero de Celular Plexsys';
COMMENT ON COLUMN GA_ABOCEL.NUM_VENTA IS 'Numero de Venta';
COMMENT ON COLUMN GA_ABOCEL.COD_MODVENTA IS 'Codigo de Modalidad de Venta';
COMMENT ON COLUMN GA_ABOCEL.COD_TIPCONTRATO IS 'Tipo de Contrato Venta';
COMMENT ON COLUMN GA_ABOCEL.NUM_CONTRATO IS 'Numero de Contrato';
COMMENT ON COLUMN GA_ABOCEL.NUM_ANEXO IS 'Numero de Anexo Contrato';
COMMENT ON COLUMN GA_ABOCEL.FEC_CUMPLAN IS 'Fecha Posible Cambio Plan Tarifario';
COMMENT ON COLUMN GA_ABOCEL.COD_CREDMOR IS 'Codigo de Limite Credito de Morosidad';
COMMENT ON COLUMN GA_ABOCEL.COD_CREDCON IS 'Codigo de Limite Credito de Consumo';
COMMENT ON COLUMN GA_ABOCEL.COD_CICLO IS 'Codigo de Ciclo Facturacion';
COMMENT ON COLUMN GA_ABOCEL.IND_FACTUR IS 'Indicativo de Facturable ; No (0), Si (1)';
COMMENT ON COLUMN GA_ABOCEL.IND_SUSPEN IS 'Indicativo de Suspendible ; No (0), Si (1)';
COMMENT ON COLUMN GA_ABOCEL.IND_REHABI IS 'Indicativo de Rehabilitable ; No (0), Si (1)';
COMMENT ON COLUMN GA_ABOCEL.IND_INSGUIAS IS 'Indicativo de Insercion en Guias ; No (0), Si (1)';
COMMENT ON COLUMN GA_ABOCEL.FEC_FINCONTRA IS 'Fecha de Fin Contrato';
COMMENT ON COLUMN GA_ABOCEL.FEC_RECDOCUM IS 'Fecha de Recepcion Documentacion';
COMMENT ON COLUMN GA_ABOCEL.FEC_CUMPLIMEN IS 'Fecha de Cumplimentacion Datos';
COMMENT ON COLUMN GA_ABOCEL.FEC_ACEPVENTA IS 'Fecha de Aceptacion Venta';
COMMENT ON COLUMN GA_ABOCEL.FEC_ACTCEN IS 'Fecha de Activacion en Central';
COMMENT ON COLUMN GA_ABOCEL.FEC_BAJA IS 'Fecha de Baja';
COMMENT ON COLUMN GA_ABOCEL.FEC_BAJACEN IS 'Fecha de Baja en Central';
COMMENT ON COLUMN GA_ABOCEL.FEC_ULTMOD IS 'Fecha de Ultima Modificacion';
COMMENT ON COLUMN GA_ABOCEL.COD_CAUSABAJA IS 'Codigo de Causa de Baja';
COMMENT ON COLUMN GA_ABOCEL.NUM_PERSONAL IS 'Codigo de Bloqueo de Terminal';
COMMENT ON COLUMN GA_ABOCEL.IND_SEGURO IS 'Indicativo de Seguro ; Si (0), No (1)';
COMMENT ON COLUMN GA_ABOCEL.CLASE_SERVICIO IS 'Matricula de Servicios contratados por el Abonado';
COMMENT ON COLUMN GA_ABOCEL.PERFIL_ABONADO IS 'Matricula de Servicios Activos del Abonado';
COMMENT ON COLUMN GA_ABOCEL.NUM_MIN IS 'Prefijo MIN';
COMMENT ON COLUMN GA_ABOCEL.IND_DISP IS 'Indicativo de Disponibilidad 0:No disponible (STP) 1:Disponible';
COMMENT ON COLUMN GA_ABOCEL.COD_PASSWORD IS 'Password de acceso via Internet.';
COMMENT ON COLUMN GA_ABOCEL.IND_PASSWORD IS 'Indicador de validez de password: 0=valida | 1=invalida.';
COMMENT ON COLUMN GA_ABOCEL.COD_AFINIDAD IS 'Codigo de afinidad';
COMMENT ON COLUMN GA_ABOCEL.FEC_PRORROGA IS 'Fecha de Prorroga de Contrato';
COMMENT ON COLUMN GA_ABOCEL.IND_EQPRESTADO IS 'Indicador de equipo prestado';
COMMENT ON COLUMN GA_ABOCEL.FLG_CONTDIGI IS 'Indica si el contrato esta digitalizado.';
COMMENT ON COLUMN GA_ABOCEL.FEC_ALTANTRAS IS 'Indica la fecha de alta anterior, dado que se hizo un traspaso..';
COMMENT ON COLUMN GA_ABOCEL.NUM_IMEI IS 'Numero Serie Terminal GSM';
COMMENT ON COLUMN GA_ABOCEL.COD_TECNOLOGIA IS 'Codigo Tecnologia';
COMMENT ON COLUMN GA_ABOCEL.NUM_MIN_MDN IS 'MIN asociado al Numero Celular (funcion logistica).';
COMMENT ON COLUMN GA_ABOCEL.COD_OFICINA_PRINCIPAL IS 'Codigo Oficina Principal';
COMMENT ON COLUMN GA_ABOCEL.COD_CAUSA_VENTA IS 'Codigo de Causa deVenta';
COMMENT ON COLUMN GA_ABOCEL.COD_OPERACION IS 'Codigo de Operacion';
COMMENT ON COLUMN GA_ABOCEL.COD_PRESTACION IS 'Prestacion de la linea, ver GE_PRESTACIONES_TD';
COMMENT ON COLUMN GA_ABOCEL.MTO_VALOR_REFERENCIA IS 'Valor de Referencia por minuto';
COMMENT ON COLUMN GA_ABOCEL.COD_MONEDA IS 'moneda del valor de referencia del minuto';
COMMENT ON COLUMN GA_ABOCEL.TIPO_PRIMARIACARRIER IS 'Tipologia Primaria (servicio 144) carrier';
COMMENT ON COLUMN GA_ABOCEL.OBS_INSTANCIA IS 'observacion de instancia';


-- Índices:
CREATE INDEX ABOCEL_CIUDADES_IF ON GA_ABOCEL (COD_REGION, COD_PROVINCIA, COD_CIUDAD);
CREATE INDEX AK_GA_ABOCEL_CAUSABAJA ON GA_ABOCEL (COD_PRODUCTO, COD_CAUSABAJA);
CREATE INDEX AK_GA_ABOCEL_CELDAS ON GA_ABOCEL (COD_CELDA);
CREATE INDEX AK_GA_ABOCEL_CENTPLEX ON GA_ABOCEL (COD_PRODUCTO, COD_CENTRAL_PLEX);
CREATE INDEX AK_GA_ABOCEL_CENTRALES ON GA_ABOCEL (COD_PRODUCTO, COD_CENTRAL);
CREATE INDEX AK_GA_ABOCEL_CICLOS ON GA_ABOCEL (COD_CICLO);
CREATE INDEX AK_GA_ABOCEL_CLIENTE ON GA_ABOCEL (COD_CLIENTE);
CREATE INDEX AK_GA_ABOCEL_CUENTAS ON GA_ABOCEL (COD_CUENTA, COD_SITUACION);
CREATE INDEX AK_GA_ABOCEL_EMPRESA ON GA_ABOCEL (COD_EMPRESA);
CREATE INDEX AK_GA_ABOCEL_ESTADOS ON GA_ABOCEL (COD_ESTADO);
CREATE INDEX AK_GA_ABOCEL_GRPSERV ON GA_ABOCEL (COD_PRODUCTO, COD_GRPSERV);
CREATE INDEX AK_GA_ABOCEL_HOLDING ON GA_ABOCEL (COD_HOLDING);
CREATE INDEX AK_GA_ABOCEL_LIMCONSUMO ON GA_ABOCEL (COD_PRODUCTO, COD_LIMCONSUMO);
CREATE INDEX AK_GA_ABOCEL_LIMCONSUMOCOB ON GA_ABOCEL (COD_CREDCON, COD_PRODUCTO);
CREATE INDEX AK_GA_ABOCEL_LIMCREDITO ON GA_ABOCEL (COD_CREDMOR, COD_PRODUCTO);
CREATE INDEX AK_GA_ABOCEL_MODVENTA ON GA_ABOCEL (COD_MODVENTA);
CREATE INDEX AK_GA_ABOCEL_NUMCELULAR ON GA_ABOCEL (NUM_CELULAR);
CREATE INDEX AK_GA_ABOCEL_NUMSERIE ON GA_ABOCEL (NUM_SERIE);
CREATE INDEX AK_GA_ABOCEL_OPCARRIER ON GA_ABOCEL (COD_CARRIER);
CREATE INDEX AK_GA_ABOCEL_OPREDFIJA ON GA_ABOCEL (COD_OPREDFIJA);
CREATE INDEX AK_GA_ABOCEL_PLANSERV ON GA_ABOCEL (COD_PRODUCTO, COD_PLANSERV);
CREATE INDEX AK_GA_ABOCEL_PLANTARIF ON GA_ABOCEL (COD_PRODUCTO, COD_PLANTARIF);
CREATE INDEX AK_GA_ABOCEL_SITUABO ON GA_ABOCEL (COD_SITUACION);
CREATE INDEX AK_GA_ABOCEL_SUBCUENTAS ON GA_ABOCEL (COD_SUBCUENTA);
CREATE INDEX AK_GA_ABOCEL_TIPCONTRATO ON GA_ABOCEL (COD_PRODUCTO, COD_TIPCONTRATO);
CREATE INDEX AK_GA_ABOCEL_TIPTERMINAL ON GA_ABOCEL (COD_PRODUCTO, TIP_TERMINAL);
CREATE INDEX AK_GA_ABOCEL_USOS ON GA_ABOCEL (COD_USO);
CREATE INDEX AK_GA_ABOCEL_USUARIO ON GA_ABOCEL (COD_USUARIO);
CREATE INDEX AK_GA_ABOCEL_VENTAS ON GA_ABOCEL (NUM_VENTA);
CREATE INDEX GA_ABOCEL_NUM_IMEI_IE ON GA_ABOCEL (NUM_IMEI);
CREATE INDEX GA_ABOC_CAUSAVENTA_IF ON GA_ABOCEL (COD_OPERACION, COD_CAUSA_VENTA);
CREATE INDEX NUK_GA_ABOCEL_PASSWORD_TMC ON GA_ABOCEL (COD_PASSWORD);

-- Llave primaria:
ALTER TABLE GA_ABOCEL ADD CONSTRAINT PK_GA_ABOCEL PRIMARY KEY (NUM_ABONADO);

--28.ICG_NIVELSERVICIO
-- Descripción: Niveles de servicio.

CREATE TABLE ICG_NIVELSERVICIO (
  COD_PRODUCTO  INTEGER                    NOT NULL,
  COD_SERVICIO  INTEGER                    NOT NULL,
  COD_NIVEL     INTEGER                    NOT NULL,
  DES_NIVEL     VARCHAR(50)                NOT NULL
);

-- Llave primaria:

ALTER TABLE ICG_NIVELSERVICIO ADD CONSTRAINT PK_ICG_NIVELSERVICIO 
  PRIMARY KEY (COD_PRODUCTO, COD_SERVICIO, COD_NIVEL);

--29.GA_SERVSUPL
-- Descripción: Servicios suplementarios.

CREATE TABLE GA_SERVSUPL (
  COD_PRODUCTO      INTEGER                   NOT NULL,
  COD_SERVICIO      VARCHAR(3)                NOT NULL,
  COD_SERVSUPL      INTEGER                   NOT NULL,
  COD_NIVEL         INTEGER                   NOT NULL,
  DES_SERVICIO      VARCHAR(40)               NOT NULL,
  IND_AUTMAN        VARCHAR(1)                NOT NULL,
  IND_COMERC        INTEGER                   DEFAULT 1                     NOT NULL,
  IND_PRO           INTEGER                   DEFAULT 1                     NOT NULL,
  IND_CENTRAL       INTEGER,
  COD_APLIC         VARCHAR(180),
  IND_TRASPASO      INTEGER                   DEFAULT 0,
  DES_SERVICIO_WEB  VARCHAR(80),
  IND_GESTOR        INTEGER                   DEFAULT 0,
  IND_COBRO         INTEGER                   DEFAULT 0,
  IND_PRIORIDAD     INTEGER                   DEFAULT 3                     NOT NULL,
  TIP_SERVICIO      VARCHAR(5)                DEFAULT '1'                   NOT NULL,
  IND_TUXEDO        INTEGER                   DEFAULT 0,
  IND_INFRANET      INTEGER                   DEFAULT 0,
  SUB_CATEGORIA     VARCHAR(10),
  TIP_RED           VARCHAR(1)                DEFAULT 'M'                   NOT NULL,
  IND_IP            INTEGER                   DEFAULT 0,
  TIP_COBRO         VARCHAR(1)                DEFAULT 'V',
  IND_COBRETR       INTEGER                   DEFAULT 0,
  IND_RESTRINGIBLE  INTEGER                   DEFAULT 0
);

-- Índices en PostgreSQL:

CREATE INDEX AK_GA_SERVSUPL_NIVELSERVICIO ON GA_SERVSUPL (COD_PRODUCTO, COD_SERVSUPL, COD_NIVEL);

-- Llave primaria:

ALTER TABLE GA_SERVSUPL ADD CONSTRAINT PK_GA_SERVSUPL PRIMARY KEY (COD_PRODUCTO, COD_SERVICIO);

-- Restricción de validación en PostgreSQL:

ALTER TABLE GA_SERVSUPL ADD CHECK (IND_INFRANET IN (0,1));

--30.GA_SERVSUPLABO
-- Descripción: Servicios suplementarios de abonados.

CREATE TABLE GA_SERVSUPLABO (
  NUM_ABONADO    BIGINT                   NOT NULL,
  COD_SERVICIO   VARCHAR(3)              NOT NULL,
  FEC_ALTABD     DATE                     NOT NULL,
  COD_SERVSUPL   INTEGER                  NOT NULL,
  COD_NIVEL      INTEGER                  NOT NULL,
  COD_PRODUCTO   INTEGER                  NOT NULL,
  NUM_TERMINAL   VARCHAR(15)              NOT NULL,
  NOM_USUARORA   VARCHAR(30)              NOT NULL,
  IND_ESTADO     INTEGER                  DEFAULT 1                     NOT NULL,
  FEC_ALTACEN    DATE,
  FEC_BAJABD     DATE,
  FEC_BAJACEN    DATE,
  COD_CONCEPTO   INTEGER,
  NUM_DIASNUM    BIGINT,
  COD_PRIORIDAD  INTEGER,
  IND_DESBORDE   VARCHAR(3)
) ;

-- Comentarios:
COMMENT ON TABLE GA_SERVSUPLABO IS 'Servicios Suplementarios de Abonados';
COMMENT ON COLUMN GA_SERVSUPLABO.NUM_ABONADO IS 'Numero de Abonado/Producto';
COMMENT ON COLUMN GA_SERVSUPLABO.COD_SERVICIO IS 'Codigo de Servicio';
COMMENT ON COLUMN GA_SERVSUPLABO.FEC_ALTABD IS 'Fecha de Alta en Base de Datos';
COMMENT ON COLUMN GA_SERVSUPLABO.COD_SERVSUPL IS 'Codigo de Servicio Suplementario';
COMMENT ON COLUMN GA_SERVSUPLABO.COD_NIVEL IS 'Nivel de Servicio Suplementario';
COMMENT ON COLUMN GA_SERVSUPLABO.COD_PRODUCTO IS 'Codigo de Producto';
COMMENT ON COLUMN GA_SERVSUPLABO.NUM_TERMINAL IS 'Numero de Terminal (Identificador Producto)';
COMMENT ON COLUMN GA_SERVSUPLABO.NOM_USUARORA IS 'Nombre de Usuario';
COMMENT ON COLUMN GA_SERVSUPLABO.IND_ESTADO IS 'Indicativo de Estado del Servicio; (1) Alta B.D., (2) Alta Central, (3) Baja B.D., (4) Baja Central';
COMMENT ON COLUMN GA_SERVSUPLABO.FEC_ALTACEN IS 'Fecha de Alta en Central';
COMMENT ON COLUMN GA_SERVSUPLABO.FEC_BAJABD IS 'Fecha de Baja en Base de Datos';
COMMENT ON COLUMN GA_SERVSUPLABO.FEC_BAJACEN IS 'Fecha de Baja en Central';
COMMENT ON COLUMN GA_SERVSUPLABO.COD_CONCEPTO IS 'Concepto de Facturacion Asociado';
COMMENT ON COLUMN GA_SERVSUPLABO.NUM_DIASNUM IS 'Numero de asociacion con dias especiales o friends and family';
COMMENT ON COLUMN GA_SERVSUPLABO.COD_PRIORIDAD IS 'Prioridad entre Servicios Suplementarios';
COMMENT ON COLUMN GA_SERVSUPLABO.IND_DESBORDE IS 'Indicador de desborde de aplicacion del SS al consumir sus unidades libres: DPT desborda hacia el Plan Tarifario, DSS hacia otro Servicios Suplementarios y ND no Desborda';

-- Índices:
CREATE INDEX AK_GA_SERVSUPLABO_CONCEPTOS ON GA_SERVSUPLABO (COD_CONCEPTO);
CREATE INDEX AK_GA_SERVSUPLABO_SERVSUPL ON GA_SERVSUPLABO (COD_PRODUCTO, COD_SERVICIO);
CREATE INDEX AK_GA_SERVSUPLABO_USUARORA ON GA_SERVSUPLABO (NOM_USUARORA);
CREATE INDEX GA_SERVSUPLABO_SERVGRUPO_IE ON GA_SERVSUPLABO (COD_SERVICIO, COD_SERVSUPL, IND_ESTADO);

-- Llave primaria:
ALTER TABLE GA_SERVSUPLABO ADD CONSTRAINT PK_GA_SERVSUPLABO PRIMARY KEY (NUM_ABONADO, COD_SERVICIO, FEC_ALTABD);

--31.GA_INTARCEL
-- Descripción: Información sobre la interfaz de abonados de red celular.

CREATE TABLE GA_INTARCEL (
  COD_CLIENTE      BIGINT                   NOT NULL,
  NUM_ABONADO      BIGINT                   NOT NULL,
  IND_NUMERO       INTEGER                  DEFAULT 1                     NOT NULL,
  FEC_DESDE        DATE                     NOT NULL,
  FEC_HASTA        DATE                     NOT NULL,
  IMP_LIMCONSUMO   NUMERIC(14,4)            NOT NULL,
  IND_FRIENDS      INTEGER                  NOT NULL,
  IND_DIASESP      INTEGER                  NOT NULL,
  COD_CELDA        VARCHAR(7)               NOT NULL,
  TIP_PLANTARIF    VARCHAR(1)               NOT NULL,
  COD_PLANTARIF    VARCHAR(3)               NOT NULL,
  NUM_SERIE        VARCHAR(25)              NOT NULL,
  NUM_CELULAR      BIGINT                   NOT NULL,
  COD_CARGOBASICO  VARCHAR(3)               NOT NULL,
  COD_CICLO        INTEGER                  NOT NULL,
  COD_PLANCOM      BIGINT                   NOT NULL,
  COD_PLANSERV     VARCHAR(3)               NOT NULL,
  COD_GRPSERV      VARCHAR(2)               NOT NULL,
  COD_GRUPO        BIGINT,
  COD_PORTADOR     INTEGER,
  COD_USO          INTEGER                  DEFAULT 4                     NOT NULL,
  NUM_IMSI         VARCHAR(25),
  NUM_MIN_MDN      VARCHAR(15)
);

-- Comentarios:
COMMENT ON COLUMN GA_INTARCEL.COD_USO IS 'Codigo de uso.';
COMMENT ON COLUMN GA_INTARCEL.NUM_IMSI IS 'IMSI asociado a la SIMCARD';
COMMENT ON COLUMN GA_INTARCEL.NUM_MIN_MDN IS 'Min asociado al numero de celular';

-- Índices:
CREATE INDEX AK1_GA_INTARCEL ON GA_INTARCEL (NUM_IMSI);
CREATE INDEX AK_GA_INTARCEL ON GA_INTARCEL (NUM_CELULAR, FEC_DESDE);
CREATE INDEX GA_INTARCEL_IDX_004 ON GA_INTARCEL (COD_CLIENTE, NUM_ABONADO, FEC_DESDE, FEC_HASTA, NUM_CELULAR, NUM_SERIE);

-- Llave primaria:
ALTER TABLE GA_INTARCEL ADD CONSTRAINT PK_GA_INTARCEL PRIMARY KEY (COD_CLIENTE, NUM_ABONADO, IND_NUMERO, FEC_DESDE);

--Llaves foráneas:

--COD_PRODUCTO (entidades relacionadas: TA_PLANTARIF, GE_PRODUCTOS, ICG_CENTRAL, GA_TIPCONTRATO, GA_PLANSERV, GA_ABOCEL, ICG_NIVELSERVICIO, GA_SERVSUPL, GA_SERVSUPLABO)

ALTER TABLE TA_PLANTARIF
ADD CONSTRAINT FK_TA_PLANTARIF_PRODUCTO
FOREIGN KEY (COD_PRODUCTO)
REFERENCES GE_PRODUCTOS (COD_PRODUCTO);

ALTER TABLE ICG_CENTRAL
ADD CONSTRAINT FK_ICG_CENTRAL_PRODUCTO
FOREIGN KEY (COD_PRODUCTO)
REFERENCES GE_PRODUCTOS (COD_PRODUCTO);

ALTER TABLE GA_TIPCONTRATO
ADD CONSTRAINT FK_GA_TIPCONTRATO_PRODUCTO
FOREIGN KEY (COD_PRODUCTO)
REFERENCES GE_PRODUCTOS (COD_PRODUCTO);

ALTER TABLE GA_PLANSERV
ADD CONSTRAINT FK_GA_PLANSERV_PRODUCTO
FOREIGN KEY (COD_PRODUCTO)
REFERENCES GE_PRODUCTOS (COD_PRODUCTO);

ALTER TABLE GA_ABOCEL
ADD CONSTRAINT FK_GA_ABOCEL_PRODUCTO
FOREIGN KEY (COD_PRODUCTO)
REFERENCES GE_PRODUCTOS (COD_PRODUCTO);

ALTER TABLE ICG_NIVELSERVICIO
ADD CONSTRAINT FK_ICG_NIVELSERVICIO_PRODUCTO
FOREIGN KEY (COD_PRODUCTO)
REFERENCES GE_PRODUCTOS (COD_PRODUCTO);

ALTER TABLE GA_SERVSUPL
ADD CONSTRAINT FK_GA_SERVSUPL_PRODUCTO
FOREIGN KEY (COD_PRODUCTO)
REFERENCES GE_PRODUCTOS (COD_PRODUCTO);

ALTER TABLE GA_SERVSUPLABO
ADD CONSTRAINT FK_GA_SERVSUPLABO_PRODUCTO
FOREIGN KEY (COD_PRODUCTO)
REFERENCES GE_PRODUCTOS (COD_PRODUCTO);

--COD_CATEGORIA (entidades relacionadas: GE_CATEGORIAS, GA_CUENTAS, GE_CLIENTES)

ALTER TABLE GE_CATEGORIAS 
ADD CONSTRAINT UQ_GE_CATEGORIAS_COD_CATEGORIA 
UNIQUE (COD_CATEGORIA);
ALTER TABLE GA_CUENTAS 
ADD CONSTRAINT FK_GA_CUENTAS_COD_CATEGORIA 
FOREIGN KEY (COD_CATEGORIA) 
REFERENCES GE_CATEGORIAS(COD_CATEGORIA);
ALTER TABLE GE_CLIENTES 
ADD CONSTRAINT FK_GE_CLIENTES_COD_CATEGORIA 
FOREIGN KEY (COD_CATEGORIA) 
REFERENCES GE_CATEGORIAS(COD_CATEGORIA);

--COD_CLASCTA (entidades relacionadas: GE_CLASCTA, GA_CUENTAS)

ALTER TABLE GE_CLASCTA 
ADD CONSTRAINT UQ_GE_CLASCTA_COD_CLASCTA 
UNIQUE (COD_CLASCTA);
ALTER TABLE GA_CUENTAS 
ADD CONSTRAINT FK_GA_CUENTAS_COD_CLASCTA 
FOREIGN KEY (COD_CLASCTA) 
REFERENCES GE_CLASCTA(COD_CLASCTA);

--COD_TIPIDENT (entidades relacionadas: GE_TIPIDENT, GA_CUENTAS, GE_CLIENTES)

ALTER TABLE GA_CUENTAS
ADD CONSTRAINT FK_GA_CUENTAS_TIPIDENT
FOREIGN KEY (COD_TIPIDENT)
REFERENCES GE_TIPIDENT (COD_TIPIDENT);

ALTER TABLE GE_CLIENTES
ADD CONSTRAINT FK_GE_CLIENTES_TIPIDENT
FOREIGN KEY (COD_TIPIDENT)
REFERENCES GE_TIPIDENT (COD_TIPIDENT);

--COD_TIPTARJETA (entidades relacionadas: GE_TIPTARJETAS, GE_CLIENTES)

ALTER TABLE GE_CLIENTES
ADD CONSTRAINT FK_GE_CLIENTES_TIPTARJETA
FOREIGN KEY (COD_TIPTARJETA)
REFERENCES GE_TIPTARJETAS (COD_TIPTARJETA);

--COD_BANCO (entidades relacionadas: GE_SUCURSALES, GE_BANCOS, GE_CLIENTES)

ALTER TABLE GE_SUCURSALES
ADD CONSTRAINT FK_GE_SUCURSALES_BANCO
FOREIGN KEY (COD_BANCO)
REFERENCES GE_BANCOS (COD_BANCO);

ALTER TABLE GE_CLIENTES
ADD CONSTRAINT FK_GE_CLIENTES_BANCO
FOREIGN KEY (COD_BANCO)
REFERENCES GE_BANCOS (COD_BANCO);

--COD_SUCURSAL (entidades relacionadas: GE_SUCURSALES, GE_CLIENTES)

ALTER TABLE GE_CLIENTES
ADD CONSTRAINT FK_GE_CLIENTES_SUCURSAL
FOREIGN KEY (COD_BANCO, COD_SUCURSAL)
REFERENCES GE_SUCURSALES (COD_BANCO, COD_SUCURSAL);

--COD_SISPAGO (entidades relacionadas: GE_SISPAGO, GE_CLIENTES)
ALTER TABLE GE_CLIENTES
ADD CONSTRAINT FK_GE_CLIENTES_SISPAGO
FOREIGN KEY (COD_SISPAGO)
REFERENCES GE_SISPAGO (COD_SISPAGO);

--COD_PAIS (entidades relacionadas: GE_PAISES, GE_CLIENTES)

ALTER TABLE GE_CLIENTES
ADD CONSTRAINT FK_GE_CLIENTES_PAIS
FOREIGN KEY (COD_PAIS)
REFERENCES GE_PAISES (COD_PAIS);

--COD_REGION (entidades relacionadas: GE_REGIONES, GE_PROVINCIAS, GE_COMUNAS, GE_OFICINAS, GA_ABOCEL)

ALTER TABLE GE_PROVINCIAS
ADD CONSTRAINT FK_GE_PROVINCIAS_REGION
FOREIGN KEY (COD_REGION)
REFERENCES GE_REGIONES (COD_REGION);

ALTER TABLE GE_COMUNAS
ADD CONSTRAINT FK_GE_COMUNAS_REGION
FOREIGN KEY (COD_REGION)
REFERENCES GE_REGIONES (COD_REGION);

ALTER TABLE GE_OFICINAS
ADD CONSTRAINT FK_GE_OFICINAS_REGION
FOREIGN KEY (COD_REGION)
REFERENCES GE_REGIONES (COD_REGION);

ALTER TABLE GA_ABOCEL
ADD CONSTRAINT FK_GA_ABOCEL_REGION
FOREIGN KEY (COD_REGION)
REFERENCES GE_REGIONES (COD_REGION);

--COD_PROVINCIA (entidades relacionadas: GE_PROVINCIAS, GE_COMUNAS, GE_OFICINAS, GA_ABOCEL)

ALTER TABLE GE_COMUNAS
ADD CONSTRAINT FK_GE_COMUNAS_PROVINCIA
FOREIGN KEY (COD_PROVINCIA, COD_REGION)
REFERENCES GE_PROVINCIAS (COD_PROVINCIA, COD_REGION);

ALTER TABLE GE_OFICINAS
ADD CONSTRAINT FK_GE_OFICINAS_PROVINCIA
FOREIGN KEY (COD_PROVINCIA, COD_REGION)
REFERENCES GE_PROVINCIAS (COD_PROVINCIA, COD_REGION);

ALTER TABLE GA_ABOCEL
ADD CONSTRAINT FK_GA_ABOCEL_PROVINCIA
FOREIGN KEY (COD_PROVINCIA, COD_REGION)
REFERENCES GE_PROVINCIAS (COD_PROVINCIA, COD_REGION);

--COD_OFICINA (entidades relacionadas: GE_OFICINAS, GE_CLIENTES)

ALTER TABLE GE_CLIENTES
ADD CONSTRAINT FK_GE_CLIENTES_OFICINA
FOREIGN KEY (COD_OFICINA)
REFERENCES GE_OFICINAS (COD_OFICINA);

--COD_CALCLIEN (entidades relacionadas: GE_CALCLIENTE, GE_CLIENTES)

ALTER TABLE GE_CLIENTES
ADD CONSTRAINT FK_GE_CLIENTES_CALCLIEN
FOREIGN KEY (COD_CALCLIEN)
REFERENCES GE_CALCLIENTE (COD_CALCLIEN);

--COD_ACTIVIDAD (entidades relacionadas: GE_ACTIVIDADES, GE_CLIENTES)

ALTER TABLE GE_CLIENTES
ADD CONSTRAINT FK_GE_CLIENTES_ACTIVIDAD
FOREIGN KEY (COD_ACTIVIDAD)
REFERENCES GE_ACTIVIDADES (COD_ACTIVIDAD);

--COD_ALM (entidades relacionadas: GE_ALMS, ICG_CENTRAL)

ALTER TABLE ICG_CENTRAL
ADD CONSTRAINT FK_ICG_CENTRAL_ALM
FOREIGN KEY (COD_ALM)
REFERENCES GE_ALMS (COD_ALM);

--COD_CLIENTE (entidades relacionadas: GE_CLIENTES, GA_ABOCEL, GA_INTARCEL)

ALTER TABLE GA_ABOCEL
ADD CONSTRAINT FK_GA_ABOCEL_CLIENTE
FOREIGN KEY (COD_CLIENTE)
REFERENCES GE_CLIENTES (COD_CLIENTE);

ALTER TABLE GA_INTARCEL
ADD CONSTRAINT FK_GA_INTARCEL_CLIENTE
FOREIGN KEY (COD_CLIENTE)
REFERENCES GE_CLIENTES (COD_CLIENTE);

--COD_CELDA (entidades relacionadas: GE_CELDAS, GA_ABOCEL, GA_INTARCEL)

ALTER TABLE GA_ABOCEL
ADD CONSTRAINT FK_GA_ABOCEL_CELDA
FOREIGN KEY (COD_CELDA)
REFERENCES GE_CELDAS (COD_CELDA);

ALTER TABLE GA_INTARCEL
ADD CONSTRAINT FK_GA_INTARCEL_CELDA
FOREIGN KEY (COD_CELDA)
REFERENCES GE_CELDAS (COD_CELDA);

--COD_TIPCONTRATO (entidades relacionadas: GA_TIPCONTRATO, GA_ABOCEL)

ALTER TABLE GA_ABOCEL
ADD CONSTRAINT FK_GA_ABOCEL_TIPCONTRATO
FOREIGN KEY (COD_TIPCONTRATO, COD_PRODUCTO)
REFERENCES GA_TIPCONTRATO (COD_TIPCONTRATO, COD_PRODUCTO);

--COD_PLANSERV (entidades relacionadas: GA_PLANSERV, GA_ABOCEL, GA_INTARCEL)

ALTER TABLE GA_ABOCEL
ADD CONSTRAINT FK_GA_ABOCEL_PLANSERV
FOREIGN KEY (COD_PLANSERV, COD_PRODUCTO)
REFERENCES GA_PLANSERV (COD_PLANSERV, COD_PRODUCTO);

ALTER TABLE GA_PLANSERV
ADD CONSTRAINT UQ_GA_PLANSERV_COD_PLANSERV UNIQUE (COD_PLANSERV);

ALTER TABLE GA_INTARCEL
ADD CONSTRAINT FK_GA_INTARCEL_PLANSERV
FOREIGN KEY (COD_PLANSERV)
REFERENCES GA_PLANSERV (COD_PLANSERV);

--COD_CICLO (entidades relacionadas: FA_CICLOS, GA_INTARCEL)

ALTER TABLE GA_INTARCEL
ADD CONSTRAINT FK_GA_INTARCEL_CICLO
FOREIGN KEY (COD_CICLO)
REFERENCES FA_CICLOS (COD_CICLO);

--NUM_ABONADO (entidades relacionadas: GA_ABOCEL, GA_SERVSUPLABO, GA_INTARCEL)

ALTER TABLE GA_SERVSUPLABO
ADD CONSTRAINT FK_GA_SERVSUPLABO_NUM_ABONADO
FOREIGN KEY (NUM_ABONADO)
REFERENCES GA_ABOCEL (NUM_ABONADO);

ALTER TABLE GA_INTARCEL
ADD CONSTRAINT FK_GA_INTARCEL_NUM_ABONADO
FOREIGN KEY (NUM_ABONADO)
REFERENCES GA_ABOCEL (NUM_ABONADO);
